### ISSUE TITLE
Add a .prf "feature file" for QMake for simpler builds

### ISSUE THREAD

**Issue by jankusanagi** [qxmpp-project/qxmpp#100]
Apparently, QXMPP doesn't include a .prf file, which other Qt-based libraries use to allow easy (and safe) "feature inclusion" when creating makefiles with qmake, from a .pro file.

If a library provides such a feature file, an application which uses it, and uses qmake as buildsystem, can just have a line like "CONFIG += qxmpp" (whatever the name of the .prf file is), and then, there's no need to manually link to qxmpp with something like "LIBS += -lqxmpp", and the include files are guaranteed to be in the include path.

The main advantage is the assurance that the library to link will be correct, regardless of the actual name the library file has in the system (like libqxmpp-qt5, or whatever a specific distribution ends up calling it).

If a GNU/linux distribution wants to use a different name for some reason, or provide both qt4 and qt5 co-installable builds, they can tune this .prf file, and the apps depending on QXMPP don't need to worry about this.

Samples:
**QOAuth**: https://github.com/ayoy/qoauth/blob/master/oauth.prf
**QCA**: https://quickgit.kde.org/?p=qca.git&a=blob&h=f25440f244ad0249d9a29df77a4f81949a277542&f=crypto.prf.cmake&o=plain
(I don't know why this one is called .prf.cmake, but the result is just crypto.prf)

You can see on their README their instructions to start using QOAuth:
https://github.com/ayoy/qoauth/blob/master/README#L31

Thanks!!

EDIT: similar to what's provided in the qxmpp.pc file that's generated when qxmpp is built.

**Comment by jlaine** [comment]
Sounds good to me, would you mind providing a pull request?

**Comment by jankusanagi** [comment]
Great!

I don't mind providing a pull request, although I don't think I'm really qualified for this xD

I've prepared a file that seems to work for my setup, based on the one from QOAuth. I'll provide a PR in a moment, but it will probably need some checking from someone more "in the know" about this. Especially the part targeting other non-GNU OSes :p

**Comment by jankusanagi** [comment]
Done!

https://github.com/qxmpp-project/qxmpp/pull/101
