### ISSUE TITLE
XEP-280 support discussion 

### ISSUE THREAD

**Issue by LightZam** [qxmpp-project/qxmpp#107]
i need behavior that documented in xep-280
http://xmpp.org/extensions/xep-0280.html

any suggestion for this xep when i implement?

**Comment by 0xd34df00d** [comment]
You might borrow something like

https://github.com/0xd34df00d/leechcraft/blob/master/src/plugins/azoth/plugins/xoox/carbonsmanager.h
https://github.com/0xd34df00d/leechcraft/blob/master/src/plugins/azoth/plugins/xoox/carbonsmanager.cpp

**Comment by LightZam** [comment]
wow, awesome!
is there a reason that this carbonsmanager wasn't merge to QXMPP?

**Comment by LightZam** [comment]
i found out #88 was implement this protocol, any problem to merge it?
@jlaine @0xd34df00d
