### ISSUE TITLE
QDnsLookup requires a QCoreApplication

### ISSUE THREAD

**Issue by Omardavinci** [qxmpp-project/qxmpp#108]
solved close

The code:
cliente.connectToServer("email","password");

i use this slot:
connect (ui->botonConectar,SIGNAL(clicked()),this,SLOT(conectar()));

**Comment by Omardavinci** [comment]
I get the same error in example_0_connected 
https://postimg.org/image/fv5zp9pm9/

**Comment by jlaine** [comment]
What version of Qt are you using? In the past, such errors occured because users compiled QXmpp against one major version of Qt, and compiled their app against another.

**Comment by Omardavinci** [comment]
i am using qt 5.7 and i am using static libraries and compiles fine and anyways when i run the example i get the same message so i dont know i can take more details if you need?

**Comment by Omardavinci** [comment]
i need to use old version?

**Comment by Omardavinci** [comment]
all examples take me the same error so i think the fault is qt not your code

**Comment by Omardavinci** [comment]
maybe i need to use one old version? it is strange because with qt 5.7 takes this error i use static build

**Comment by Omardavinci** [comment]
only using the example i get this error 
picture:
https://postimg.org/image/fv5zp9pm9/

and i ge tthis error in all examples

**Comment by Omardavinci** [comment]
i think the project is off. Because the examples in qt 5.7 take the same the error. I dont know if it works in olders

**Comment by Omardavinci** [comment]
maybe i need to include this: DQXMPP_STATIC ??? how i include this to the project of xmpp?

**Comment by Omardavinci** [comment]
i didnt solve it anyways

**Comment by Omardavinci** [comment]
I am using example_0_connected and i get the same message so i think the compiler doesnt compile well or some error in the code or something is wrong

**Comment by Omardavinci** [comment]
you can solve if you create a QDnsLoopup object before you've created a QCoreApplication object i think

**Comment by Omardavinci** [comment]
i will check code and i say you if i got some update useful

**Comment by Omardavinci** [comment]
about this error how i can solve? with other compiler? or using other version? some technical idea about this?

**Comment by Omardavinci** [comment]
maybe the source code need some update?

**Comment by Omardavinci** [comment]
Anyways i am using this: win32-g++ to compile so in the past this was tested and works i dont know why now doesnt work??

**Comment by jlaine** [comment]
I seriously doubt this error is related to an error in QXmpp. I suggest you write a minimal application (linked only against Qt, not QXmpp) which makes use of QDnsLookup and see whether it produces the same error.

**Comment by Omardavinci** [comment]
when i included the class #include <QDnsLookup> it doesnt recognize? it is usual? sorry i am still newbie in qt

**Comment by Omardavinci** [comment]
i tried but i got some errors not like this error. I was trying to do a minimal application with qdnslookup but

**Comment by Omardavinci** [comment]
Ok i did minimal application so this is the result that i got:
When i do the dinamically compilation, works fine.
But when i do static compilation happens this:
Starting C:\Qt\Qt5.2.0\Tools\QtCreator\bin\build-qdnslookup-Unnamed-Debug\debug\qdnslookup.exe...
The program has unexpectedly finished.
C:\Qt\Qt5.2.0\Tools\QtCreator\bin\build-qdnslookup-Unnamed-Debug\debug\qdnslookup.exe crashed

So maybe are you right? In my case it is the static build the problem????

**Comment by Omardavinci** [comment]
Hi men i did minimal application like this:
void MainWindow::lookupServers()
{
    // Create a DNS lookup.
    QDnsLookup *dns = new QDnsLookup(this);
    connect(dns, SIGNAL(finished()),
            this, SLOT(handleServers()));

    // Find the XMPP servers for gmail.com
    dns->setType(QDnsLookup::SRV);
    dns->setName("_xmpp-client._tcp.gmail.com");
    dns->lookup();
}

Works fine in static and dinamyc so i dont know why xmpp take me this problem thx and regards

**Comment by Omardavinci** [comment]
some update about this? i am trying to fix but i dont have the enough level i am still newbie in qt

**Comment by Omardavinci** [comment]
i tried with other compilers nothing i dont know why show me this message

**Comment by Omardavinci** [comment]
lol man you are right now works fine i used shared libraries and works thx a lot sorry again

**Comment by Omardavinci** [comment]
i use compiler msvc2013

**Comment by Omardavinci** [comment]
solved

**Comment by jlaine** [comment]
You have opened half a dozen issues impatiently asking for help, and in the end you just say "solved". Could you please at least have the courtesy to say what was wrong and how you solved your issue?

**Comment by jlaine** [comment]
No response from submitter for 2 years.

**Comment by Rhylx** [comment]
Hi, I have had the same issue on Windows 10 with MSVC c++ compiler and didn't knew what to do to solve this during quite a long time. For the record I want to give the solution that worked for me and could maybe help others.  
I used another SDK for Qt: [aqtinstall](https://github.com/miurahr/aqtinstall) and now it works perfectly :).
