### ISSUE TITLE
Can't connect to host with an ip adresse

### ISSUE THREAD

**Issue by YajiLI** [qxmpp-project/qxmpp#109]
Here is my code example:

		Config.setHost("123.45.678.910");
		Config.setPort(5222);
		Config.setUser("User@123.45.678.910");
		Config.setPassword("mypassword");
		Config.setJid("User2@123.45.678.910")
        _client.connectToServer(Config, QXmppPresence::Available);
		bool IsConnect=_client.isConnected();

123.45.678.910 is an example of my host ip adresse, but IsConnect is always been false and from the host side, i got error as user name false.
Does QT work with  jid host which is in IP address? If not, does anyone have another easy install library to recommend? I use VS2013 and programme in C++.

**Comment by Omardavinci** [comment]
one question you checked if the example-0 worked? In my case, i use compiler mingw and i have problems too

**Comment by YajiLI** [comment]
@Omardavinci I didn't check the example yet, and there is no error showing down my project but just didn't work for me. I'm pretty sure there is no QCoreApplication requires in my case

**Comment by Omardavinci** [comment]
which version of qt are you using?

**Comment by YajiLI** [comment]
@Omardavinci QT5.4.1 et VS2013 en Windows10

**Comment by Omardavinci** [comment]
So i think maybe didnt work with jid then i didnt know that this works fine in qt with compiler vs2013 maybe it is the only way to get to work this repository i think. Anyways maybe the problem is because you are using ip and not hostname?? i dont know about this issue more so maybe the creator of this can help you and take more details

**Comment by Omardavinci** [comment]
you can check if the examples works? maybe the syntax is wrong or maybe the repository have some error. So please check and maybe we can be sure why this happen

**Comment by Omardavinci** [comment]
please check if the examples works you can do static built and then we can sure and maybe know more about this issue thx

**Comment by YajiLI** [comment]
![image](https://cloud.githubusercontent.com/assets/10439991/18340218/0b5ab8a8-75a4-11e6-9c3c-d569c35d9d85.png)
@Omardavinci this is it when I click the .exe, i'm not sure if I launch it properly...

**Comment by Omardavinci** [comment]
Look maybe if you change the source in example_0_connected and put one email and pass correct we can check if it Works fine and we can be more sure.
Put your address and pass in the example i dont knoz if the failed connection is for closed domain or it doesnt work.
Check this please and build examples and all with your own address
code.
cliente.connectToServer("email","password"); check if the example works

**Comment by YajiLI** [comment]
@Omardavinci OK now I understand what do you mean, in my own project, I didn't have problem with connection of google talk, which means when I changed my server to google server, it can be connected. 
My bool IsConnect=_client.isConnected(); returns TRUE. So I think my compilation is good.

**Comment by Omardavinci** [comment]
one thing when you do static build of xmpp you include some command or some prefix Normally i need to put qxmpp_d0.dll in all examples . For example:
https://i.imgsafe.org/143af0806f.png

Maybe if we do bad configuration take errors? how yo did static build in your case doesnt take qxmpp dll why? So i think if your examples are working then you didnt have any problema to run your example

**Comment by YajiLI** [comment]
@Omardavinci you are right, maybe there is some problem in our config
![image](https://cloud.githubusercontent.com/assets/10439991/18348749/840fc04e-75cd-11e6-8c91-d5eb2cca1cd8.png)

**Comment by Omardavinci** [comment]
but in the sources you can put other account you can créate one and then you put in the example0. Nomally the messages must be succesfull connection i think. You can créate one account xmpp and put in sources. Because if it Works then the problema is not source.

**Comment by jlaine** [comment]
Are you aware that Qt works with signals / slots?

connectToServer does not block, you will receive a signal when connected.

If you have any error messages please post them

**Comment by Omardavinci** [comment]
in my case the error is QDnsLookup requires a QCoreApplication . Maybe i need to use the same compiler and version than him?

**Comment by jlaine** [comment]
@Omardavinci please do not pollute this issue with your separate problem

**Comment by Omardavinci** [comment]
you solved your problem?? 9 days after???
