### ISSUE TITLE
Is SASLandSCRAM-SHA-1 auth supported?

### ISSUE THREAD

**Issue by varnav** [qxmpp-project/qxmpp#112]
Hello!

Does QXmpp support SCRAM-SHA-1 auth mechanism?

https://wiki.xmpp.org/web/SASLandSCRAM-SHA-1

**Comment by jlaine** [comment]
Not currently, but I would welcome an implementation of this for client + server

**Comment by varnav** [comment]
There is a chance we can do it. I'm creating a ticket in our company internal Jira for it.

**Comment by jlaine** [comment]
As far as I can it's mostly straightforward except passwordPrep and PBKDF2

**Comment by Neustradamus** [comment]
@jlaine: This ticket can be update no?

**Comment by Neustradamus** [comment]
Linked to https://github.com/qxmpp-project/qxmpp/issues/177 :)

**Comment by lnjX** [comment]
SCRAM-SHA1 and SCRAM-SHA256 were added in https://github.com/qxmpp-project/qxmpp/commit/bce9ca477709ae0876e7b7682034f49cdd010f27
