### ISSUE TITLE
Is that correct that SSL certificate check is off by default?

### ISSUE THREAD

**Issue by varnav** [qxmpp-project/qxmpp#113]
Hello!

I'm looking at [this line](https://github.com/qxmpp-project/qxmpp/blob/master/src/client/QXmppConfiguration.cpp#L90)

Is that correct that SSL errors are ignored by default = certificates are not checked?

**Comment by jlaine** [comment]
You are absolutely right, that's horrible! I believe this a leftover from a time where most SSL configurations were incorrect.

The default definitely needs to be to not ignore SSL errors.
