### ISSUE TITLE
 parallel class to transfer files

### ISSUE THREAD

**Issue by Omardavinci** [qxmpp-project/qxmpp#117]
Sometimes when i run xmpp transfer files my firewall block me. So i was thinking to do one 
parallel class to avoid this. But i know that i can use proxy and that but it's not for my proxy. It's because when i include in my main constructor show me this message. So my question i can do one parallel class to transfer files and instance() this class all time i want to transfer files.

**Comment by lnjX** [comment]
If I did understand you right (which I'm not sure), you're suggesting that QXmpp instantiates a class whenever there's a file transfer. I don't think this is QXmpp's job and I'm not convinced this is needed.
