### ISSUE TITLE
some alternative using only pure c++

### ISSUE THREAD

**Issue by Regardmiki** [qxmpp-project/qxmpp#123]
Hi this is very complete library to make XMPP extensions, but if i want to develop using only pure c++ which is better? gloox? I ask because maybe you could recommend one useful for pure c++.  Thanks in advance

**Comment by 0xd34df00d** [comment]
Gloox also uses other libraries, like OpenSSL, for instance. How are they different from Qt from language purity point of view?

**Comment by Regardmiki** [comment]
It's only because i'm more focused in the language (c++) than in the framework that they take me additional functionalities. So first i make the logic of my program (extension xmpp) and then when i finish my extension i take support with qt.  Sometimes when someone use only qt can be tempted to do misuse of the language.
