### ISSUE TITLE
How can a gmail user chat with a linux user on a xmpp server?

### ISSUE THREAD

**Issue by necktwi** [qxmpp-project/qxmpp#124]
Ok, I have successfully built qxmpp on my server. I ran `./example_8_server mydomain.com`. I want to chat with a user on my linux server from gtalk using gmail account. How can I do it? can I do it? its the reason why I have pulled it and built it. What can I do with qxmpp server. I couldn't find any document how to use it. Thank you.

**Comment by jlaine** [comment]
To my knowledge gmail has discontinued XMPP support.
