### ISSUE TITLE
XEP-0384: OMEMO Encryption

### ISSUE THREAD

**Issue by chickeaterbanana** [qxmpp-project/qxmpp#133]
It would be greate to have OMEMO-Encryption support for this great library.

**Comment by olesalscheider** [comment]
I agree that this would be an interesting feature. Do you know if there is any library for the crypto primitives that is compatible with qxmpp's license?

But as always: Pull requests are always welcome!

**Comment by tehnick** [comment]
There is [libomemo](https://github.com/gkdr/libomemo), for example.

But in Psi IM, Psi+ and Dino xmpp clients library [libsignal-protocol-c](https://github.com/signalapp/libsignal-protocol-c) is used without extra layers...

**Comment by olesalscheider** [comment]
libsignal-protocol-c is GPL3 however. While qxmpp is LPGP 2.1 - so we can't link against it or everything will be under GPL3. libomemo needs libaxc for the the double ratchet session which is also GPL3...

**Comment by 0xd34df00d** [comment]
libomemo also seems to pass raw XML strings around which will require some additional (de)serialization of the stanzas just for the sake of encryption, which seems suboptimal.

**Comment by tehnick** [comment]
> libsignal-protocol-c is GPL3 however. While qxmpp is LPGP 2.1 - so we can't link against it or everything will be under GPL3.

And why is this a problem if this feature will be optional?

**Comment by tehnick** [comment]
Personally I have not seen C++ libraries with double ratchet implementation under more permissive licenses. There were no even announces...

**Comment by olesalscheider** [comment]
I haven't seen any either, that's why I asked. It is not a problem per se, but it means that the feature can't be used by all that use qxmpp currently and that it might be reimplemented once we have a double ratchet implementation under a permissive license. That's just why I don't want to implement it myself right now...

**Comment by 0xd34df00d** [comment]
Me neither.

I have a double ratchet implementation in mind, but arguably neither C nor C++ are good languages for implementing something security-oriented. I'm thinking of doing something provably correct in a language like Agda or Idris and then either exporting the implementation to C (in case of Agda) or providing FFI (in case of Idris), but that'll take a long time.

**Comment by Arhangel64** [comment]
Is there any way I can put some bounty on this issue?

**Comment by Neustradamus** [comment]
There is a new version XEP-0384: OMEMO Encryption: 0.4.0.

**Comment by Neustradamus** [comment]
For information, after the 0.4.0, there is a 0.5.0.
- https://xmpp.org/extensions/xep-0384.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.5.0.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html

**Comment by tehnick** [comment]
> There is a new version XEP-0384: OMEMO Encryption: 0.4.0.

It is incompatible with older versions and is not implemented in any XMPP client for this moment (I am talking about stable releases of programs)...

**Comment by Neustradamus** [comment]
@tehnick: Yes I know.

**Comment by niqt** [comment]
Make sense the porting of this https://github.com/sebastianv89/double-ratchet in C++ ?

**Comment by lnjX** [comment]
If this is just because of licensing issues, we can just separate all OMEMO specific things into an extra module. I wanted to split QXmpp up into Base/Client/Server anyways. Having an Omemo module that is GPLv3 additionally would be OK, I guess.

**Comment by lnjX** [comment]
@niqt maybe we could also use a rust FFI for this purpose? That could be easier than reimplementing everything (and might also be more secure).

**Comment by niqt** [comment]
@lnjX i think that we can use rust FFI on iOS

**Comment by Neustradamus** [comment]
@lnjX: Good job!

Little question, it is OMEMO 0.8 or OMEMO 0.8.3?

**Comment by Neustradamus** [comment]
@melvo, @lnjX: Good job!

Little question, it is OMEMO 0.8 or OMEMO 0.8.3?

**Comment by lnjX** [comment]
You probably wanted to ask whether it is 0.8.0 or 0.8.3. The patch release doesn't matter. The differences are only editorial changes in the XEP.

**Comment by Neustradamus** [comment]
@lnjX: Yes, it is for this that you can specify 0.8.3 :)

**Comment by lnjX** [comment]
@Neustradamus there's no need to specify 0.8.3 if 0.8.3 has no relevant changes compared to 0.8.0, 0.8.1, 0.8.2 and possible futures versions 0.8.4 and ongoing.
