### ISSUE TITLE
The project builds but does not runs

### ISSUE THREAD

**Issue by cmlyldz** [qxmpp-project/qxmpp#135]
After building project when I run one of the any example I get the;
 ......example_0_connected.exe exited with code -1073741515 and also qtcreator_process_stub.exe     "Press <RETURN> to close this window..."
I tried with minGW and VS2013-2015-2017, always I get the same error. 
I used qt creator 4.5.1 and qt 5.10.1. on windows 10.

**Comment by jlaine** [comment]
Can anyone reproduce this?

**Comment by xdien** [comment]
I also tried to build on windows 7 with mingw 5.3.0, qt 5.7
I run the same source code as EchoClient on linux, it works fine. On the windown 7 it stopped at.
> DEBUG Looking up server for domain

I have turned off the firewall but still can not.

**Comment by xdien** [comment]
My problem was solved when I put the connection function inside main(). It also has the same problem here #38

**Comment by lnjX** [comment]
@xdien / @cmlyldz Is the problem still existing (in the examples) or can I close this issue?
