### ISSUE TITLE
Bus error: 10 with an small example of use of QXmppClient

### ISSUE THREAD

**Issue by jngd** [qxmpp-project/qxmpp#137]
I'm trying to use qxmpp in one MacOS application and I have one little example of bus error in my computer with the following code:

```c++

#include <QCoreApplication>
#include <QXmppMessage.h>
#include <QXmppIq.h>
#include <QXmppClient.h>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    QScopedPointer<QXmppClient> client;
    client.reset(new QXmppClient);
    QXmppConfiguration conf;
    client->connectToServer(conf);

    qDebug() << "Example finished";
    return a.exec();
}


```
In this example, building and linking against the last version of qxmpp (fresh clone of repo in this date), I always get Bus error: 10 if I launch application from terminal. If I use QtCreator debugger, I can see that application stop in client->connectToServer(conf); call. Any clue about? This is the .pro file of this example:

```qmake
QT -= gui

CONFIG += c++11 console
CONFIG -= app_bundle
QT += core network

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0
QXMPP_PATH = /path/to/qxmpp

INCLUDEPATH += $$QXMPP_PATH/src/client
INCLUDEPATH += $$QXMPP_PATH/src/server
INCLUDEPATH += $$QXMPP_PATH/src/base

LIBS += /path/to/libqxmpp_d.0.dylib

SOURCES += main.cpp

```
Any flag or plugin needed to make it run?

The example is running over:

Macbook Pro 15-inch Late 2011
MacOS HighSierra Version 10.13.1
Intel Core i7 2.2Ghz
Memory 10GB 1333 MHz DDR3
Graphics AMD Radeon HD 6750M 512 MB - Intel HD Graphics 3000 512 MB

**UPDATE: I'm using Qt 5.10.0**

**Comment by lnjX** [comment]
> If I use QtCreator debugger, I can see that application stop in client->connectToServer(conf); call. Any clue about?

Maybe it's because you're using an empty configuration. This can't work.

**Comment by lnjX** [comment]
You need to at least set a JID and a password in the QXmppConfiguration, otherwise QXmpp tries to connect to an empty host. If this doesn't fix the problem please reopen.
