### ISSUE TITLE
XEPs and RFCs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [qxmpp-project/qxmpp#138]
It is possible to have a XEPs and RFCs support page with version?
In the same time, I see that there are old RFCs, it is possible to update to new RFCs?
https://github.com/qxmpp-project/qxmpp

Examples:
- https://metronome.im/supported-xeps-list
- https://trac.gajim.org/wiki/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by jlaine** [comment]
Sure, you're welcome to submit a pull request

**Comment by Neustradamus** [comment]
From RFC6120, SCRAM-SHA-1 and SCRAM-SHA-1-PLUS are missing
- https://github.com/qxmpp-project/qxmpp/issues/177

**Comment by jlaine** [comment]
The XEPs support are listed in the documentation of each released version, e.g.:

http://doc.qxmpp.org/qxmpp-0.9.1/xep.html

For the XEPs supported by git master, refer to:

https://github.com/qxmpp-project/qxmpp/blob/master/doc/xep.doc

**Comment by Neustradamus** [comment]
@jlaine: there are not VERSION, can you reopen the ticket?

Can you see for update the code with new RFCs?
It is always the very old XMPP RFCs...

**Comment by Neustradamus** [comment]
@jlaine: Always no changes.
None:
- XEP-XXXX v1.2
- RFCXXXX
