### ISSUE TITLE
tst_qxmppversioniq.moc: No such file or directory

### ISSUE THREAD

**Issue by vasilyrud** [qxmpp-project/qxmpp#141]
When compiling on Ubuntu 16.04 I get the following error:

```
[ 34%] Building CXX object tests/CMakeFiles/tst_qxmppversioniq.dir/qxmppversioniq/tst_qxmppversioniq.cpp.o
/home/vasily/xmpp-fuzzer/qxmpp/tests/qxmppversioniq/tst_qxmppversioniq.cpp:79:34: fatal error: tst_qxmppversioniq.moc: No such file or directory
compilation terminated.
tests/CMakeFiles/tst_qxmppversioniq.dir/build.make:62: recipe for target 'tests/CMakeFiles/tst_qxmppversioniq.dir/qxmppversioniq/tst_qxmppversioniq.cpp.o' failed
make[2]: *** [tests/CMakeFiles/tst_qxmppversioniq.dir/qxmppversioniq/tst_qxmppversioniq.cpp.o] Error 1
CMakeFiles/Makefile2:273: recipe for target 'tests/CMakeFiles/tst_qxmppversioniq.dir/all' failed
make[1]: *** [tests/CMakeFiles/tst_qxmppversioniq.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

Steps to reproduce:

```
git clone https://github.com/qxmpp-project/qxmpp.git
cd qxmpp
mkdir build
cd build
cmake ..
make
```

Some details:

`cmake version 3.5.1`
`GNU Make 4.1`
`Linux version 4.4.0-116-generic`
`Using Qt version 5.5.1`

**Comment by LightZam** [comment]
if you just need it to build success, and you don't care it build in the original folder(qxmpp instead of qxmpp/build)

try
```
git clone https://github.com/qxmpp-project/qxmpp.git
cd qxmpp
cmake
make
```

**Comment by olesalscheider** [comment]
Please try if the first commit in https://github.com/qxmpp-project/qxmpp/pull/145 fixes your problem.

**Comment by jlaine** [comment]
I am unable to reproduce this issue, could you try with the latest code and let us know if the error still occurs?

**Comment by vasilyrud** [comment]
First commit in https://github.com/qxmpp-project/qxmpp/pull/145 fixes the compilation problem. (commit 98753bbaed56f5ad64e725c1164b6fe109447944)

Commit 3 at https://github.com/qxmpp-project/qxmpp/pull/145 also compiles (commit 20c9bd1713701509473bd380ced8b314723a4fdd)

Current master branch (commit 34b6a758013e3c2cec4f0e180be79a7c94260bc9) is still failing in the same way.
