### ISSUE TITLE
Examples cannot be built - no CMakeLists.txt

### ISSUE THREAD

**Issue by jlaine** [qxmpp-project/qxmpp#146]
Since the switch to CMake most of the examples have become unusable - nothing is provided to compile them.

@olesalscheider please make sure all examples can easily be built by our users.

**Comment by olesalscheider** [comment]
All examples in the `examples` subfolder are built when you set `BUILD_EXAMPLES` to `ON` when running cmake. The binaries can then be found in the `examples` subfolder inside the build folder.

Does this solve your problem or do you need more? I'm happy to provide some patch if you describe what exactly we need.

**Comment by jlaine** [comment]
Ah I see. When I saw the example wasn't build I naively cd'ed into the directory and didn't find the CMakelists.txt so assumed something was wrong. Maybe making examples opt-out instead of opt-in would make sense?

**Comment by jlaine** [comment]
Fixed by 4e66c72332aa36a8d6d33afa925b588c2b2cb88d and 0ef60d1a4e8f75b0a5658df1a880caef92b98f20
