### ISSUE TITLE
How to construct Iq stanza

### ISSUE THREAD

**Issue by IMAN4K** [qxmpp-project/qxmpp#148]
Hi.

I'm wondering how we could send message with the following structure via `qxmpp`:
```xml
<iq type="set" to="{Bare JID}" id="3">
  <subscribe xmlns="google:push">
    <item channel="cloudprint.google.com" from="cloudprint.google.com"/>
  </subscribe>
</iq>
```
This is the `<iq>` section i have done already:
```C++
        QXmppIq iq;
	iq.setType(QXmppIq::Type::Set);
	iq.setTo(/*<hash>@cloudprint.googleusercontent.com*/);
	iq.setId("3");
```
How add `<subscribe>` section ?

Regards.

**Comment by jlaine** [comment]
`QXmppIq` merely serves as a base class, from which specialised IQ classes inherit. The best would be for you to define a class for these Google push IQs, and a corresponding manager class to send/handle them.

You can look at the `QXmppCarbonManager` for instance, which is a fairly simple manager class.
