### ISSUE TITLE
release version 1.0.0

### ISSUE THREAD

**Issue by jlaine** [qxmpp-project/qxmpp#156]
It's been ages since we've had a proper release.

We need to feed the changelog with everything that landed since 0.9.3 then we can tag / push our first cmake-based release

**Comment by jlaine** [comment]
@tehnick I'm not sure I understand why this should delay a source release, I see no problem if Debian/Ubuntu packaging only happens a week or so later.

**Comment by tehnick** [comment]
@jlaine Sorry, I have missed your message somehow.

> I'm not sure I understand why this should delay a source release, I see no problem if Debian/Ubuntu packaging only happens a week or so later.

Unfortunately, I do not have strong arguments for this, but only personal wishes to test deb packages with library before stable release is out. Sometimes this is allows to find different issues.

I have updated [packaging rules](https://github.com/tehnick/qxmpp-devel-debian/commits/launchpad) of [devel package](https://launchpad.net/~tehnick/+archive/ubuntu/qxmpp-devel/+packages) and tested it a bit. As far as I see library works fine. I have found only one [problem with Doxygen documentation](https://github.com/qxmpp-project/qxmpp/issues/158) and [tiny typo](https://github.com/qxmpp-project/qxmpp/commit/b74badb6d3bebb21f35c53924c3a478b33dade3d) in text string.

**Comment by tehnick** [comment]
Also there are few more differences:
- in qmake-based packages:

```
-rw-r--r--  root/root   /usr/lib/x86_64-linux-gnu/libqxmpp.so.0.9.3
lrwxrwxrwx  root/root   /usr/lib/x86_64-linux-gnu/libqxmpp.so -> libqxmpp.so.0.9.3
lrwxrwxrwx  root/root   /usr/lib/x86_64-linux-gnu/libqxmpp.so.0 -> libqxmpp.so.0.9.3
lrwxrwxrwx  root/root   /usr/lib/x86_64-linux-gnu/libqxmpp.so.0.9 -> libqxmpp.so.0.9.3
```
- in cmake-based packages:
```
-rw-r--r--  root/root   /usr/lib/x86_64-linux-gnu/libqxmpp.so.0.9.4
lrwxrwxrwx  root/root   /usr/lib/x86_64-linux-gnu/libqxmpp.so -> libqxmpp.so.0
lrwxrwxrwx  root/root   /usr/lib/x86_64-linux-gnu/libqxmpp.so.0 -> libqxmpp.so.0.9.4
```
But this is just a note. No changes are necessary.

**Comment by tehnick** [comment]
@jlaine 
I have fixed generating of Doxygen documentation. It looks that nothing prevents from new stable release now.

But why do you want to release version 0.9.5 instead of 0.9.4? More over, personally I would vote for version 1.0.0...

Also could you sign new git tag with your gnupg key this time? It is very simple.

**Comment by tehnick** [comment]
@0xd34df00d What do you think about next stable version?

**Comment by tehnick** [comment]
@0xd34df00d Also it would be nice if you could test the library before release. Maybe I have missed something that should be fixed...

**Comment by 0xd34df00d** [comment]
@tehnick haven't paid attention to my inbox for a few days, sorry! I'll rebuild my stuff with the current HEAD and let you know if I encounter any issues with it over the next couple of days.

Overall I'm very positive about making a release!

**Comment by 0xd34df00d** [comment]
Also, I second @tehnick on this. Turns out I haven't rebuilt qxmpp for quite some time, so the live package in Gentoo got outdated (as it's still based on qmake). I'll have to update that one first.

**Comment by jlaine** [comment]
> But why do you want to release version 0.9.5 instead of 0.9.4? More over, personally I would vote for version 1.0.0...

0.9.5 was a typo, I meant 0.9.4. 1.0.0 is also fine by me, no strong feelings on the topic.

> Also could you sign new git tag with your gnupg key this time? It is very simple.

Sure.

**Comment by jlaine** [comment]
Let's see if we can land #159 soon, would be a nice addition.

**Comment by tehnick** [comment]
Hi there,

Is it time to release qxmpp `v1.0.0` now?

Personally I would vote for improving of #160 and merging before release.
All other look ready for usage. (After switching to cmake.)

**Comment by jlaine** [comment]
Can someone start feeding the CHANGELOG so we can finally cut the release?

**Comment by lnjX** [comment]
@jlaine See #180. I didn't include many small commits, I hope everything is ok so.

**Comment by jlaine** [comment]
@lnjX is really doing a fantastic job!

I have just merged PR #180

**Comment by lnjX** [comment]
Is everything ready now?

**Comment by tehnick** [comment]
Personally I am ready to update package in Debian when new version will be released.

**Comment by tehnick** [comment]
This is not a reason for hurry up, but just for a note:
[2019-01-12](https://wiki.debian.org/DebianBuster#Before_the_release) - Transition freeze in Debian Buster

**Comment by lnjX** [comment]
I think we've got everything for the v1.0, my pull requests (and also my [work on HTTP File Upload](https://git.kaidan.im/kaidan/kaidan/tree/master/src/qxmpp-exts)) can go in later. We could do another release in a few months then.

**Comment by tehnick** [comment]
Build logs and static code analysis look fine:
https://launchpad.net/~tehnick/+archive/ubuntu/qxmpp-devel/+packages
https://sibuserv-ci.org/projects/qxmpp/v0.9.3-78-ge24ed7b

**Comment by jlaine** [comment]
I have tagged v1.0.0 (with a signature as requested by @tehnick)

**Comment by jlaine** [comment]
Documentation is up at http://doc.qxmpp.org/qxmpp-1.0.0/

**Comment by tehnick** [comment]
> I have tagged v1.0.0 (with a signature as requested by @tehnick)

Thanks!

Unfortunately, you forgot to update [changelog](https://github.com/qxmpp-project/qxmpp/blob/master/CHANGELOG.md) this time:
> QXmpp 1.0.0 (UNRELEASED)

Hope that next release will be done easier.

**Comment by jlaine** [comment]
Ah shit, I can nuke the tag a re-apply it. More importantly I thought of something else: the SOVERSION should probably go up to 1 as we are switching from Qt4 to Qt5?

**Comment by tehnick** [comment]
> Ah shit, I can nuke the tag a re-apply it.

I do not think this is a good idea. You may just add new tag `v1.0.1`.

> More importantly I thought of something else: the SOVERSION should probably go up to 1 as we are switching from Qt4 to Qt5?

No. Switching from Qt4 to Qt5 is not related to SOVERSION at all. SOVERSION should be bumped when library API is changed and become incompatible.

**Comment by tehnick** [comment]
BTW, our packages in Debian and Ubuntu were switched to Qt5 since 2015.

**Comment by jlaine** [comment]
@tehnick in the end I decided to retag at 1.0.0. Should all be OK now

**Comment by lnjX** [comment]
@jlaine You should probably also add a commit to continue with version 1.0.1 (as before with 0.9.4 instead of 0.9.3).

**Comment by jlaine** [comment]
@lnjX done in b4200ad6619d69287156b9c86c1cf838666d5ca1

**Comment by tehnick** [comment]
> Yep, I am already working on it.

https://buildd.debian.org/status/package.php?p=qxmpp

**Comment by jlaine** [comment]
You are awesome Boris :)

**Comment by tehnick** [comment]
@jlaine
Unfortunately I misinformed you about necessity of updating of SOVERSION. See details here:
https://bugs.debian.org/919487
There is no need in new git tag. I'll just add a patch to Debian package. Please send a reply with any comments to that bug report in Debian BTS.
