### ISSUE TITLE
Is it possible to build different arch by cmake

### ISSUE THREAD

**Issue by LightZam** [qxmpp-project/qxmpp#157]
it is easy to found, How to build a arm64, armv7, arm64-v8a, etc in Qt

but there is no document about build instruction in cmake

could you provide a way to build different arch?

**Comment by olesalscheider** [comment]
You have to write a toolchain file in which you specify the paths to your tools, where to look for libraries, and so on. You can find information about this here: https://cmake.org/cmake/help/v3.6/manual/cmake-toolchains.7.html#cross-compiling-for-linux

Then you just call cmake with -DCMAKE_TOOLCHAIN_FILE=...

**Comment by tehnick** [comment]
In case of build for Android look at:
```
/path/to/android-ndk-<ndk-version>/build/cmake/android.toolchain.cmake
```

**Comment by jlaine** [comment]
@LightZam did this answer your question?

**Comment by LightZam** [comment]
@jlaine yes, it can be use -DCMAKE_TOOLCHAIN_FILE=toolchain and use toolchain for each paltform
