### ISSUE TITLE
Problem with generating of Doxygen documentation

### ISSUE THREAD

**Issue by tehnick** [qxmpp-project/qxmpp#158]
Steps to reproduce:
```
cd ~/Hobby/Devel/QXmpp/qxmpp__git
mkdir builddir
cd builddir
cmake .. -DBUILD_DOCUMENTATION=ON -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON \
         -DWITH_OPUS=ON -DWITH_SPEEX=ON -DWITH_THEORA=ON -DWITH_VPX=ON
make -j8
find doc/html -type f > doc.html.log
```
As you may see in [doc.html.log](https://github.com/qxmpp-project/qxmpp/files/2457381/doc.html.log) this is not a proper Doxygen documentation.

For comparing look at documentation in official [Debian package](https://packages.debian.org/stretch/all/libqxmpp-doc/filelist).

Any ideas?

**Comment by jlaine** [comment]
I'm seeing some warnings about non-existent files:

https://travis-ci.org/qxmpp-project/qxmpp/jobs/438419890#L1208

**Comment by jlaine** [comment]
Replacing the DOXYGEN_INPUT line with the following "works":

```
set(DOXYGEN_INPUT "${CMAKE_CURRENT_SOURCE_DIR}/index.doc ${CMAKE_CURRENT_SOURCE_DIR}/using.doc ${CMAKE_CURRENT_SOURCE_DIR}/xep.doc ${PROJECT_SOURCE_DIR}/src")
```

However I'm pretty sure that doesn't handle spaces in directory names properly. @olesalscheider what's the CMake-ish way to do what we want here?

**Comment by tehnick** [comment]
https://cmake.org/cmake/help/v3.12/module/FindDoxygen.html

**DOXYGEN_INPUT**

Projects should not set this variable. It will be populated with the set of files and directories passed to `doxygen_add_docs()`, thereby providing consistent behavior with the other built-in commands like `add_executable()`, `add_library()` and `add_custom_target()`. If a variable named **DOXYGEN_INPUT** is set by the project, it will be ignored and a warning will be issued.
