### ISSUE TITLE
Android not supported?

### ISSUE THREAD

**Issue by IlyaBizyaev** [qxmpp-project/qxmpp#162]
When building an XMPP chat client with QXmpp, I get this error in adb logs:
`Not yet supported on Android`

I investigated a bit and found this: http://code.qt.io/cgit/qt/qtbase.git/tree/src/network/kernel/qdnslookup_android.cpp

Does this mean QXmpp is not supported on Android?

**Comment by LNJ2** [comment]
The problem seems to be known since 2013 already:
http://lists.qt-project.org/pipermail/android-development/2013-February/000056.html
And the QTBUG is opened since 2016:
https://bugreports.qt.io/browse/QTBUG-56143

**Comment by jlaine** [comment]
QXmpp itself doesn't have any android-specific issues, but you are right Qt does not support SRV DNS lookups yet. I seem to remember the suggestion was to use libcares to implement it. In any case this should be fixed in Qt itself.

**Comment by IlyaBizyaev** [comment]
It turns out Gloox uses A records as a fallback on Android.
I tried a similar approach with QXmpp and was able to fix the issue by using QHostInfo.
Maybe it can be upstreamed to make QXmpp usable on Android before the feature is implemented in Qt? (2 years w/o activity now).
