### ISSUE TITLE
Memory leak: socket is not delete in QXmppStreamPrivate 

### ISSUE THREAD

**Issue by examyes** [qxmpp-project/qxmpp#163]
this is my fix:
File: QXmppStream.cpp

class QXmppStreamPrivate
{
public:
    QXmppStreamPrivate();
    ~QXmppStreamPrivate();

    QByteArray dataBuffer;
    QSslSocket* socket;

    // incoming stream state
    QByteArray streamStart;

    bool streamManagementEnabled;
    QMap<unsigned, QByteArray> unacknowledgedStanzas;
    unsigned lastOutgoingSequenceNumber;
    unsigned lastIncomingSequenceNumber;
};

QXmppStreamPrivate::QXmppStreamPrivate()
    : socket(0), streamManagementEnabled(false), lastOutgoingSequenceNumber(0), lastIncomingSequenceNumber(0)
{
}

QXmppStreamPrivate::~QXmppStreamPrivate()
{
    delete socket;
}

**Comment by jlaine** [comment]
Have you actually *observed* a memory leak (using tools such as valgrind), or do you *suppose* it leaks from looking at the code?

As far as I can tell, the code does not leak. The socket always has a parent QObject (the incoming/outgoing client/server object), so it gets deleted when the parent does:

https://github.com/qxmpp-project/qxmpp/blob/3e2ca3c04a5a681fa97ebabf6f31b301ec9753a0/src/client/QXmppOutgoingClient.cpp#L183
https://github.com/qxmpp-project/qxmpp/blob/3e2ca3c04a5a681fa97ebabf6f31b301ec9753a0/src/server/QXmppOutgoingServer.cpp#L64
https://github.com/qxmpp-project/qxmpp/blob/3e2ca3c04a5a681fa97ebabf6f31b301ec9753a0/src/server/QXmppServer.cpp#L709
https://github.com/qxmpp-project/qxmpp/blob/3e2ca3c04a5a681fa97ebabf6f31b301ec9753a0/src/server/QXmppServer.cpp#L835

**Comment by tehnick** [comment]
> As far as I can tell, the code does not leak.

+1

Also such trivial memory leak would be easily found by static code analyzers.

**Comment by examyes** [comment]
Sorry, I didn't notice it. You are correct.
