### ISSUE TITLE
using qxmpp in raspberry pi3 and ReSpeaker 2-Mics Pi HAT sound card

### ISSUE THREAD

**Issue by velad** [qxmpp-project/qxmpp#169]
hello,
we are developing applications for voip solutions in embedded systems on raspberry pi board,in a simple call program we  have wrote in Qt, we used qxmpp for two way audio call and its worked fine with external usb sound card, but with [ReSpeaker 2-Mics Pi HAT sound card](http://wiki.seeedstudio.com/ReSpeaker_2_Mics_Pi_HAT/) we have no sound in each raspberry pi board. this car is using i2c and i2s protocols for connection to board and a driver that ssuccessfuly installed on board.

**Comment by jlaine** [comment]
I'm not sure I understand what you mean since QXmpp doesn't touch your sound devices.

**Comment by lnjX** [comment]
This seems to be either an Qt or firmware issue, but it's not a QXmpp problem. (I think the issue can be closed)

**Comment by lnjX** [comment]
@velad Is your alsa/pulseaudio config correct?
