### ISSUE TITLE
SCRAM-SHA-1 and SCRAM-SHA-1-PLUS + SCRAM-SHA-256 and SCRAM-SHA-256-PLUS supports

### ISSUE THREAD

**Issue by Neustradamus** [qxmpp-project/qxmpp#177]
SCRAM-SHA-1 and SCRAM-SHA-1-PLUS:
- https://tools.ietf.org/html/rfc5802
- https://tools.ietf.org/html/rfc6120

SCRAM-SHA-256 and SCRAM-SHA-256-PLUS:
- https://tools.ietf.org/html/rfc7677
- https://tools.ietf.org/html/draft-ietf-mile-xmpp-grid

**Comment by jlaine** [comment]
Do you plan to implement it or is this an "I would like this" issue? As there is no text in your issue it's hard to tell.

**Comment by Neustradamus** [comment]
For be simple: People request it ^^

**Comment by jlaine** [comment]
Good, then "people" can start coding.

**Comment by Neustradamus** [comment]
Nice :)
Maybe you can look for SCRAM-SHA-512 in the same time ^^
- https://xmpp.org/extensions/inbox/hash-recommendations.html from https://xmpp.org/extensions/xep-0300.html

**Comment by jlaine** [comment]
The XEPs you linked don't deal with authentication, nor do they mention SCRAM-SHA-256.

Instead of feeding me your shopping list, could you try the PR I linked against a server which supports SCRAM-SHA-1 and SCRAM-SHA-512 and confirm it actually works?

**Comment by Neustradamus** [comment]
SCRAM-SHA-1 and -PLUS and SCRAM-SHA-256 and -PLUS are from previous links

**Comment by jlaine** [comment]
SCRAM-SHA-1 and SCRAM-SHA-256 are in master.

I was able to use SCRAM-SHA-1 on jabber.at, I haven't found a usable server for SCRAM-SHA-256 so I'll leave that up to you to test. As for the -PLUS variants I don't think QSslSocket has APIs allowing us to perform the required cryptographic binding.

**Comment by lnjX** [comment]
I can test the PR at the weekend.

**Comment by jlaine** [comment]
Cool. Some notes:

- I included test vectors from the RFCs in the test suite so I'm 99% sure it's correct
- we don't have an implementation of saslPrep so using weird Unicode codepoints will probably fail (but this was already true for other mechanisms)
- it's probably time to change the preferred SASL mechanism, which is currently DIGEST-MD5
- when the preferred SASL mechanism is not available we don't have an order of next-best mechanism, we take whatever the first supported mechanism offered by the server is. Not ideal

**Comment by Neustradamus** [comment]
@jlaine Please do not close it before -PLUS variant and 512 part too...

**Comment by jlaine** [comment]
@Neustradamus please try to be a more considerate community member. Your messages come across as orders, you haven't demonstrated you are willing to do any work yourself and didn't read what I wrote:

> As for the -PLUS variants I don't think QSslSocket has APIs allowing us to perform the required cryptographic binding

The only difference of the -PLUS variants is that they establish a binding to the "channel" (in our case a TCP connection using TLS). As far as I can tell, the bindings we could use (see RFC 5929):

- `tls-unique` QSslSocket does not provide access to the `TLS Finished` message
- `tls-server-end-point` QSslCertificate does not provide the `signatureAlgorithm`

https://tools.ietf.org/html/rfc5929

**Comment by maranda** [comment]
> @Neustradamus please try to be a more considerate community member.
On that I lost every hope years ago already.
Otherwise what is the error you get? There were missing SHA-384/512 imports before 3.11.5 so those two algorithms didn't work while being advertised.
I would also like to point out that the IETF didn't officially approve usage of any algorithm beyond SHA-256 so while Metronome implements those it's rather unadvised to use/implement anything beyond SHA-256.

**Comment by Neustradamus** [comment]
SHA-512 is in the XEP-0300 split: https://xmpp.org/extensions/inbox/hash-recommendations.html from https://xmpp.org/extensions/xep-0300.html.

**Comment by maranda** [comment]
@jlaine not home so I can't properly check and might be wrong, but the digest lengths in that authentication flow looks fairly short at a first glance to myself for SHA-512 at least.

**Comment by jlaine** [comment]
Un-base64'ing the message it looks like:

**auth**

`n,,n=qxmpp,r=KHAOrntdBawLbMw9ZKf31ZjFsBsIp2P7v1Qx310NXlk=`

**challenge**

`r=KHAOrntdBawLbMw9ZKf31ZjFsBsIp2P7v1Qx310NXlk=a1aa85f8-b7ba-4e3f-a1bd-5872d29ba5ce,s=YmQ3NGQ0OTMtNTBiOS00MWQzLTk4MzQtNjJhNzUyMTE4M2Iz,i=4096`

**response** (64 byte client proof)

`c=biws,r=KHAOrntdBawLbMw9ZKf31ZjFsBsIp2P7v1Qx310NXlk=a1aa85f8-b7ba-4e3f-a1bd-5872d29ba5ce,p=h0WD1w27EWImbxTwmHUuOO0Jlf0IBQej3QBlOOiiJeZaMwNDeLPc8tDKFnVUQYODqLnR5FGl8lEc31A5NNamBg==`

**Comment by maranda** [comment]
@jlaine the computed key from the client response doesn't match the one stored by Metronome, did run a manual test on the Lua interpreter, I think the provided proof might be incorrect:

> authmessage="n=qxmpp,r=KHAOrntdBawLbMw9ZKf31ZjFsBsIp2P7v1Qx310NXlk="..",".."r=KHAOrntdBawLbMw9ZKf31ZjFsBsIp2P7v1Qx310NXlk=a1aa85f8-b7ba-4e3f-a1bd-5872d29ba5ce,s=YmQ3NGQ0OTMtNTBiOS00MWQzLTk4MzQtNjJhNzUyMTE4M2Iz,i=4096"..",".."c=biws,r=KHAOrntdBawLbMw9ZKf31ZjFsBsIp2P7v1Qx310NXlk=a1aa85f8-b7ba-4e3f-a1bd-5872d29ba5ce"

> clientsig=hmac_sha512(from_hex("04d73c64fec6daf49840d4b51282cf1d1f70a675d4ee65a7a7737374d1ec1026b778ad518838465a8fa51c6a50472fcf0e4c89dc15fc708d0fc04882608e988c"),authmessage)
serversig=hmac_sha512(from_hex("447008be5d513472b66dc46e9fb7afbe0d3fe516cfffcdeaac4d77974d163ffa4e25827b4dadfa19ce96930d7e28ed09e9d2760e1246cad03362951707e0007a"),authmessage)

> clientkey=binaryXOR(clientsig,decode("h0WD1w27EWImbxTwmHUuOO0Jlf0IBQej3QBlOOiiJeZaMwNDeLPc8tDKFnVUQYODqLnR5FGl8lEc31A5NNamBg=="))

> =sha512(clientkey, true)
f635d29dd32bba8af657d275184f9016403e79439982976e26fcf497ed694ecccfb86c0512271269a02ddfa51fbf5c5083d3a1f387dadfc032babcc3e7883ddb

I did hastily replicate a test to check, the computed key hash by Metronome based on the response is **f635d29dd32bba8af657d275184f9016403e79439982976e26fcf497ed694ecccfb86c0512271269a02ddfa51fbf5c5083d3a1f387dadfc032babcc3e7883ddb** while it should really be **04d73c64fec6daf49840d4b51282cf1d1f70a675d4ee65a7a7737374d1ec1026b778ad518838465a8fa51c6a50472fcf0e4c89dc15fc708d0fc04882608e988c** … I don't think Metronome is at fault here but should you figure otherwise feel free to open an issue and I'll fix it as soon as possible.

**Comment by jlaine** [comment]
Your test doesn't tell me anything new, we already know that qxmpp and metronome's code don't agree, running it manually won't change that! ;)

**Comment by Neustradamus** [comment]
@maranda :S

**Comment by jlaine** [comment]
@neustradamus : re-read my comments, it is fundamentally not possible short of changing Qt

**Comment by Neustradamus** [comment]
RFC8600 has been published for SCRAM-SHA256(-PLUS) and for replace old SCRAM-SHA1(-PLUS)
- https://tools.ietf.org/html/rfc8600

**Comment by Neustradamus** [comment]
@jlaine, @maranda: Psi IM works now (not -PLUS variants because Qt problem).

SCRAM-SHA-1 to 512(-PLUS) have been integrated in Cyrus SASL.

For you information, and if you want to follow, to help...
- https://bugreports.qt.io/browse/QTBUG-77783
- https://bugs.kde.org/show_bug.cgi?id=411184

**Comment by Neustradamus** [comment]
@jlaine: Can you test QXmpp (SCRAM-SHA-1/SCRAM-SHA-256/SCRAM-SHA-512) with Jackal XMPP Server and confirm if the problem is in Metronome IM?
- https://github.com/ortuman/jackal
- jackal.im

Thanks a lot in advance.

cc: @ortuman

**Comment by Neustradamus** [comment]
@maranda: Can you look the Metronome IM fix from @pasis?
@jlaine: Now you can add a real support in QXmpp :)
@lnjX: Can you look for Kaidan and maybe directly for QXmpp?

A big thanks to @pasis :)

**Comment by Neustradamus** [comment]
Dear @qxmpp-project team, @lnjX, @jlaine, @tehnick, @0xd34df00d,

It is possible to comment this Qt important ticket about Channel Binding?
- https://bugreports.qt.io/browse/QTBUG-77783

It is to needed to have support of SCRAM-SHA-*-PLUS variants.

Thanks in advance.
