### ISSUE TITLE
QXmpp MUC?

### ISSUE THREAD

**Issue by lnjX** [qxmpp-project/qxmpp#178]
Is there a QXmpp public MUC? If not, could you create one?

**Comment by jankusanagi** [comment]
It would be nice to have =)

**Comment by lnjX** [comment]
@jlaine and @tehnick Would you join and officially link a QXmpp MUC created by me?

**Comment by jlaine** [comment]
No problem linking it, however I don't expect to join it as I'm winding down my involvement.

**Comment by tehnick** [comment]
@lnjX My involvement in project is minimal now as you see and it is mostly focused on packaging of library for Debian and Ubuntu users. And I am interested in good quality of code base of course, but I do not have enough time to analyze all new commits, and I do not want to that this delay the progress of development in any way.

While @jlaine is winding down his involvement to project I think what you (or other active developer) should become new lead developer and process things in according to your (or his(her)) vision of library future.

As for MUC, I do not think it will be useful for increasing speed of qxmpp development, but it may be really useful for libqxmpp users, if anyone will be able to answer on people questions there on regular basis.

**Comment by tehnick** [comment]
> While @jlaine is winding down his involvement to project I think what you (or other active developer) should become new lead developer and process things in according to your (or his(her)) vision of library future.

This is normal life cycle of software in FOSS world. :-)
There are a lot of examples of this...

**Comment by lnjX** [comment]
> While @jlaine is winding down his involvement to project I think what you (or other active developer) should become new lead developer and process things in according to your (or his(her)) vision of library future.

I can understand that and I would be interested in becoming the new lead developer. :) Of course I would like to see someone else reviewing my stuff to avoid mistakes and improve the code quality. Since you are not having much time I'm sure I can get someone else from the Kaidan team to do that (@manchito? :D).

My personal visions for the long run would or could be:
 * Maybe making QXmpp a KDE project
 * Modularizing the core client
 * Implementing different connection back-ends like websockets or BOSH (for running QXmpp in the browser using WebAssembly) and also make use of direct tls (xmpps) if available
 * Implementing the new important XEPs (with full managers ;)
 * Splitting the library into modules: base, client, server, consistencolors (separate module because of the QColor / QtGui dependency)
 * Improving the test framework for managers: simulating incoming packages and checking outgoing packages.
 * Using a JID class instead of QStrings

However most of that is really not urgent; for me 'only' the new features (including PEP, MIX, e2ee / OMEMO) are really important.

**Comment by jlaine** [comment]
@lnjX I have sent you an invitation to join the team

**Comment by tehnick** [comment]
> Maybe making QXmpp a KDE project

Please do not do this with qxmpp!

I almost hate KDE infrastructure. (I am forced to use it for maintaining of few Debian packages and this is painful...)

**Comment by 0xd34df00d** [comment]
I strongly second Boris' sentiment.

**Comment by lnjX** [comment]
> @lnjX I have sent you an invitation to join the team

I was on holiday the last days. Thank your very much! :)

---

> > Maybe making QXmpp a KDE project
> 
> Please do not do this with qxmpp!
> 
> I almost hate KDE infrastructure. (I am forced to use it for maintaining of few Debian packages and this is painful...)

Why is that? (As a developer) I did not have any major problems with it.

**Comment by lnjX** [comment]
@jlaine I noticed I don't have write access to the QXmpp repo.

**Comment by jlaine** [comment]
> @jlaine I noticed I don't have write access to the QXmpp repo.

Right, I was unable to set your role until you accepted the invitation.

@0xd34df00d @olesalscheider : heads up, @lnjX is now an owner just like yourselves. If you have a problem with this, now is the right time to say it :)

**Comment by lnjX** [comment]
There's an unofficial QXmpp MUC on qxmpp@muc.kaidan.im. Unfortunately GitHub doesn't allow `xmpp:` URIs in markdown, so I can't really link it. On https://i.kaidan.im we've got an XMPP invitation page. I could link that (https://i.kaidan.im/#qxmpp@muc.kaidan.im?join), would that be ok or is this too much of Kaidan ads?

**Comment by lnjX** [comment]
Closed by https://github.com/qxmpp-project/qxmpp/pull/437
