### ISSUE TITLE
XEP-0412: XMPP Compliance Suites 2019

### ISSUE THREAD

**Issue by Neustradamus** [qxmpp-project/qxmpp#181]
Please add support of https://xmpp.org/extensions/xep-0412.html

**Comment by Neustradamus** [comment]
@lnjX: solved?

**Comment by lnjX** [comment]
2019 is outdated and we support everything for Core Client 2020 (apart from /me). I'll see if I can implement /me and will add something to the README then.

**Comment by Neustradamus** [comment]
It is easy to update this ticket to 2020 ;)

**Comment by lnjX** [comment]
Sorry, but this issue doesn't help at all. I know that there are compliance suites. There's not even a list of what's still missing in QXmpp or what's required to complete this issue here.
