### ISSUE TITLE
CONFIG feature file for qmake-based projects is gone

### ISSUE THREAD

**Issue by jankusanagi** [qxmpp-project/qxmpp#193]
Back in 2016 I sent a PR, #101 which was ultimately merged. It provided a qxmpp.prf file that qmake-based projects can read to know how to find QXMPP's headers and how to link to it, on different systems.

Then on this commit https://github.com/qxmpp-project/qxmpp/commit/3241e63f07c5fa493788897ddfb87a201205f621 that file got deleted along with many others. I guess most of the others were related to **building QXMPP** with qmake, and since you moved to CMake, they were no longer needed.

But qxmpp.prf wasn't there for the benefit of building QXMPP itself, but to allow qmake-based projects that use QXMPP, to include it more easily.

So, could that file be restored? I doubt it harms anything.

Cheers!

**Comment by jlaine** [comment]
Feel free to submit a PR which includes this file along with the code to install it when doing make install.

**Comment by lnjX** [comment]
This ECM script could be used for generating the .pri file:
https://github.com/KDE/extra-cmake-modules/blob/master/modules/ECMGeneratePriFile.cmake

**Comment by lnjX** [comment]
This could be used to fix it:
https://github.com/qt/qtbase/blob/dev/cmake/QtPriHelpers.cmake

**Comment by lnjX** [comment]
I'm not planning to work on this (and I don't think anyone else is), so I'll close this issue.
Qt switched to cmake (while qmake is still supported though).
I don't think there're good reasons to prefer qmake over cmake (with Qt 6).
I'm still open for PRs adding such a file, but I don't think it makes sense to continue to keep this issue opened.
The interest in it seems to be low (correct me if I'm wrong).
