### ISSUE TITLE
static library: QDomDocument linking error

### ISSUE THREAD

**Issue by iddqdidkfa** [qxmpp-project/qxmpp#21]
When i comppile QXmpp as static library it doesn't include QDomDocument.
I got an error:
```
undefined symbol: _ZN12QDomDocumentC1Ev
```
But if i create QDomDocument object im my application manually - everything works fine.

**Comment by jlaine** [comment]
I do not understand your problem, but it seems unrelated to QXmpp. FYI, we perform both shared and static library compilations as part of the continuous integration:

https://travis-ci.org/qxmpp-project/qxmpp

**Comment by iddqdidkfa** [comment]
as I described before: QXmpp static labrary does not including QDomDocument. I don't know how to explain it better. I cannot use static QXmpp library if my application will not include QDomDocument manually. I understand that static library compilation works, but it doesn't mean that library works.

P.S. I'm using Qt 5.3.1
