### ISSUE TITLE
Please revert back git project name from "QXmpp" to "qxmpp"

### ISSUE THREAD

**Issue by tehnick** [qxmpp-project/qxmpp#217]
I do not know about situation in other GNU/Linux and *BSD distros, but in Debian URLs for automatic detection of updates is case-sensitive, see:
https://salsa.debian.org/xmpp-team/qxmpp/blob/master/debian/watch

Homebrew in macOS may be affected too, see:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/qxmpp.rb

Less popular projects may be affected as well.

Please revert back git project name from "QXmpp" to "qxmpp".

**Comment by lnjX** [comment]
Sorry, I wasn't aware of that. (I thought github's redirects would work in this case)
