### ISSUE TITLE
build shared library for android

### ISSUE THREAD

**Issue by khoaopentechiz** [qxmpp-project/qxmpp#229]
i'm trying to build the qxmpp shared library to import to my project.
however, as i was following the build step as specified in README
> mkdir build
> cmake .. -DCMAKE_PREFIX_PATH=/path/to/qt/5.12.4/android_arm64_v8a
> cmake --build .
while executing this step, i got this error
=======
[ 28%] Linking CXX shared library libqxmpp.so
/usr/bin/ld: /home/khoa/Qt5.12.4/5.12.4/android_arm64_v8a/lib/libQt5Network.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/qxmpp.dir/build.make:1167: src/libqxmpp.so.1.2.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:92: src/CMakeFiles/qxmpp.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
=======
so the compiler managed to build the object files, but when it the linking step, it failed.
do you guys have any idea why?

**Comment by JBBgameich** [comment]
You are currently not using the android ndk's compiler but your systems GCC. (For example /usr/bin/ld is for amd64 most likely and can't link the arm64 Qt libraries)

**Comment by JBBgameich** [comment]
For an already working setup I recommend having a look at the utils/build-android-docker.sh script from the Kaidan codebase, which is run in the kdeorg/android-arm(64)-sdk docker container.

**Comment by lnjX** [comment]
I'm closing this since it is not related to QXmpp. What we could do though is providing simple instructions for building QXmpp for android.
