### ISSUE TITLE
(Solved) link error of autotest classes using VS2017

### ISSUE THREAD

**Issue by janhec** [qxmpp-project/qxmpp#233]
and using Qt 5.13.2 free edition.
All classes/methods decorated with QXMPP_AUTOTEST_EXPORT failed to link.
The library is dynamic, which appears to be the default and is sensible, of course.
QXMPP_AUTOTEST_EXPORT was just #defined (in QXmppGlobal.h).
After changing to `#define QXMPP_AUTOTEST_EXPORT QXMPP_EXPORT` the tests compiled and linked. Not sure where the problem starts, I'm new to QXMPP. My solution is pragmatic, perhaps someone can tell me what to correct in a more proper way?
In the readme I noticed this fix:
Disable tests that require QXMPP_AUTOTEST_EXPORT (fixes #149) (@jlaine)
I don't quite get it. The tests seem fine and useful?

**Comment by olesalscheider** [comment]
Hm, I don't really have experience with windows (and this is not needed for linux).
But I assume that QXMPP_AUTOTEST_EXPORT is for the symbols of the library that should be visible for the tests but not for anything else?
I guess this was broken by the CMake port. How did qmake solve this? Build the dll twice?

**Comment by lnjX** [comment]
As your pragmatic solution works for now and I don't think anyone can really help you currently, I'll close this for now. Feel free to reopen anytime.
