### ISSUE TITLE
QDNSLookup requires QCoreApplication

### ISSUE THREAD

**Issue by ArkaneCow** [qxmpp-project/qxmpp#24]
Hello, I noticed there was an issue closed about this problem before, but I couldn't figure out how to fix it. Here is a screenshot:
![wtf](https://cloud.githubusercontent.com/assets/1429346/5497431/70313a5a-86df-11e4-884a-274a7bfc344a.PNG)
I've looked at the examples and I can't figure out what I'm doing wrong. I've commented out almost all my code and it still gives me this error. I cannot understand what I am doing wrong.
Any help would be appreciated

**Comment by jlaine** [comment]
Cannot reproduce with the exact code given here
