### ISSUE TITLE
Building error using QtCreator 3.3.0 (Qt 5.4) for Android

### ISSUE THREAD

**Issue by fpelliccioni** [qxmpp-project/qxmpp#28]
There is a problem when trying to build using QtCreator 3.3.0 (Qt 5.4) for Android

Error:

	14:51:12: Internal Error: Could not find .pro file.
	Error while building/deploying project qxmpp (kit: Android for armeabi-v7a (GCC 4.8, Qt 5.4.0))
	When executing step "Build Android APK"

Related with:
	https://bugreports.qt-project.org/browse/QTCREATORBUG-13566

Platform:
	Ubuntu Linux 64 bits
	Qt Creator 3.3.0
	Qt 5.4.0

	Building for:
		Android armeabi-v7a 
		GCC 4.8
		
	QXMPP_VERSION = 0.8.2

Temporary solution:

	In Qt Creator goto Project, Build settings
		- Disable "make install" step
		- Disable "Build apk" step on the Project's mode under the build settings.

Perhaps it would be useful to clarify the issue in the Readme file

**Comment by jlaine** [comment]
The Qt Creator bug you mentioned is now marked as fixed.
