### ISSUE TITLE
IQReceived signal not working

### ISSUE THREAD

**Issue by kodous** [qxmpp-project/qxmpp#289]
I have a client sending an IQStanza that contains another XML bloc ('let's say a <query>'), but the other client doesn't receive it. I use the signal IQReceived, but it is never emitted. I used wireshark to observe the dataFrames, and I can see the DataFrame going from the client1 to the client2, only the client2 immediately reply with an error "BadRequest" code 400 and QUERY is unknown.

**Comment by lnjX** [comment]
The signal can only be used to receive IQs of type `result` or `error`. This is useful when the result is empty / you only want to check whether there was an error.

https://github.com/qxmpp-project/qxmpp/blob/master/src/client/QXmppOutgoingClient.cpp#L644-L655

But the documentation could indeed be improved here.

**Comment by lnjX** [comment]
Btw, you don't need to use wireshark or something else, just use the QXmppLogger it can notify you about sent/received packets.

The correct way to handle IQ *requests* is adding a new QXmppClientExtension and reimplementing the handleStanza() method.

**Comment by kodous** [comment]
thank you for the reply, it was very helpful.

**Comment by lnjX** [comment]
I improved the documentation now: https://github.com/qxmpp-project/qxmpp/commit/d7da60e0537c610257df1fcee5fac6cb2afc1b17

Unfortunately the signal name is still misleading, but we can't change that easily.

**Comment by kodous** [comment]
yes I understand, but with the new documentation you added, it is so much clearer

**Comment by kodous** [comment]
i am still getting no iqStanza. I implemented the method handlestanza() and i am getting there all the stanzas received, except for the one i am waiting for. I implemented as well the logger, I can see all the messages as well, except for the one the other client (let's call it client1) sent.

so the client1 sends this IQStanza:

```
m_client = QXmppClient();
QDomDocument domDoc("payload");
QDomElement domElem = domDoc.createElement("iq");
domElem.setAttribute("from", "client1");
domElem.setAttribute("to", "client2");
domElem.setAttribute("id", "12");
domElem.setAttribute("type", "set");
QDomElement domElem2 = domDoc.createElement("query");
domElem2.setNodeValue("core");
domElem.appendChild(domElem2);
stanzaIQ.parse(domElem);
m_client->sendPacket ( stanzaIQ );
```
can you please give me a hint on what i am doing wrong ?

**Comment by lnjX** [comment]
Are you sure you sent the IQ to the correct address (full jid / with the correct resource)?
If yes, you could test it with wireshark again, but I doubt that if the other packets are received correctly that this is QXmpp problem at all.

**Comment by kodous** [comment]
and what is even more bugging, is that if I change the type of the Stanza to result, it works, the data is sent and it is passed through handlestanza()

**Comment by lnjX** [comment]
So you're trying to send an IQ (get or set) from client A to client B, but the server doesn't pass it through to client B or did I misunderstand you?

**Comment by kodous** [comment]
That's almost the situation, but i can see in wireshark that the iq ( set or get ) is sent. But when I implement the handlestanza() on the client B, i don't see it, i see all other IQs but not get or set and same goes for the logger. Which is really odd

**Comment by lnjX** [comment]
Do other IQs work (for example service discovery)?

**Comment by kodous** [comment]
yes

**Comment by lnjX** [comment]
You could try to add some debug output in QXmppStream::_q_socketReadyRead() to see what comes out of the socket. If it's not there, it's a Qt or server-side issue. If it's there, I'm sure we can find the bug.

And one thing: I hope the XML you sent is valid, otherwise QXmpp will wait for more packets to come until the string contains valid XML.

**Comment by kodous** [comment]
yes, it was handled with the handleStanza, my XML was missing something, but now it works. thanks alot for the help.

**Comment by kodous** [comment]
Actually, the problem is still here, the handleStanza is called only when the IQ type is result or Error. as I change the Type to get or set, the handleStanza is never called.
is this normal ?

**Comment by kodous** [comment]
for the same XML, when type = result/error, handleStanza is called and when type = set/get handleStanza is not called and the StanzqIQ is not received
