### ISSUE TITLE
 qmake to compile QXmpp

### ISSUE THREAD

**Issue by meichuanneiku** [qxmpp-project/qxmpp#296]
Can you provide a version that qmake can compile, and now want to use QXmpp on mobile devices

**Comment by JBBgameich** [comment]
You can also use cmake for mobile devices, Kaidan is already doing that. Maintaining two buildsystems is quite a maintainance burden, so I'm not sure the core developers will want to do that.

**Comment by lnjX** [comment]
I'm sorry, but maintaining two build systems is a no-go. Using cmake for building for Android or iOS isn't as easy as pressing the build button in qtcreator, but as @JBBgameich pointed out definitely possible.

Kaidan is compiling QXmpp for Android using the ECM (extra-cmake-modules) toolchain for android:
https://invent.kde.org/kde/kaidan/-/blob/b80166574c8c78759a1529cc70eef1125c87524f/utils/build-android.sh
And also iOS is possible:
https://invent.kde.org/kde/kaidan/-/blob/b80166574c8c78759a1529cc70eef1125c87524f/utils/build-ios.sh
You can use that as a starting point.

**Comment by JBBgameich** [comment]
@lnjX Actually recent versions of QtCreator make it as easy to build for android with cmake as with qmake, as long as you start from tge QtCreator provided cmake template.
