### ISSUE TITLE
C++17 dependency

### ISSUE THREAD

**Issue by lnjX** [qxmpp-project/qxmpp#302]
Currently we only require C++11 as Qt 5. Qt 6 will require C++17 and I'd also like to use some of the newer features of the language and std library (like `std::optional` which I think is very useful and sometimes can make the API much clearer).

C++17 would require at least g++-7 or clang-5 (for some features clang-6 or clang-7 is required) that would mean we couldn't support debian stretch and Ubuntu xenial anymore. That's not a big deal if you ask me, but I wanted to ask this question here before (especially @tehnick).

**Comment by tehnick** [comment]
> that would mean we couldn't support debian stretch and Ubuntu xenial anymore

As I see in PPA:
https://launchpad.net/~tehnick/+archive/ubuntu/qxmpp-devel
you already stopped support of Ubuntu Xenial long time ago.
And I do not remember exactly which change was the reason of that.

Ubuntu Bionic uses gcc-7.3.0, Debian Buster uses gcc-8.3.0.
So you may consider gcc-7.3.0 as minimal supported version.

**Comment by tehnick** [comment]
> And I do not remember exactly which change was the reason of that.

https://github.com/qxmpp-project/qxmpp/pull/210#issuecomment-527851946

**Comment by tehnick** [comment]
> https://github.com/qxmpp-project/qxmpp/pull/210/commits/0a7d781de75e227060b359e22bc56df9844db844

As for Debian Stretch (oldstable), which uses gcc-6.3.0 and Qt 5.7.1, it is up to you to continue its support or not. I do not prepare official backports for Debian Stretch now.

**Comment by 0xd34df00d** [comment]
As for me, I'm strongly in favor.

**Comment by lnjX** [comment]
>  you already stopped support of Ubuntu Xenial long time ago.

Ohh, right, yes. 

Actually, we *could* support older Qt versions again by replacing `qAsConst` by `std::as_const` (C++17), but this of course doesn't help us here.

> As for Debian Stretch (oldstable), which uses gcc-6.3.0 and Qt 5.7.1, it is up to you to continue its support or not. I do not prepare official backports for Debian Stretch now.

I'll drop the support then.

Thank you :)
