### ISSUE TITLE
Transfer file on Android failed!

### ISSUE THREAD

**Issue by xywgit** [qxmpp-project/qxmpp#305]
I transfer file on android is failed, The error is  connect stream host error, But i test android to window client is success,So I hop your can help me ,I want use on Android to Android client，Thanks！

**Comment by lnjX** [comment]
I haven't used Jingle File Transfer on my own, but I'd guess that something with the STUN or proxying doesn't work. Are your Android device and desktop computer in the same network? Are both android devices in the same network, too? Or is one of them for example using LTE and the other WiFi?

Generally when you want to build a modern XMPP IM client, you should use HTTP File Upload because that works asynchronously and works better with multiple devices. [Kaidan](https://www.kaidan.im/) for example uses it with QXmpp.

Just out of interest: What kind of project are you trying to build with QXmpp?

**Comment by xywgit** [comment]
I want make a IM client with Qt on Android,I used iris and gloox before,they can trans fire any environment,but the api is not easy to use,so i try  qxmpp,the qxmpp file transfer error is ‘QXmppTransferJob::ProtocolError’ and ‘<error type=\"cancel\" code=\"404\"><item-not-found xmlns=\"urn:ietf:params:xml:ns:xmpp-stanzas\"/></error>’ on Android to Android，Android to Windows no problem,windows to Android no problem too.I try the android to android in the same wifi，later i try they in the different network using LTE and the other WiFi，but not success！

There is another problem：the receive file on Android must be flush the buffer  can save right，your can check it。
Thanks

**Comment by xywgit** [comment]
> I haven't used Jingle File Transfer on my own, but I'd guess that something with the STUN or proxying doesn't work. Are your Android device and desktop computer in the same network? Are both android devices in the same network, too? Or is one of them for example using LTE and the other WiFi?
> 
> Generally when you want to build a modern XMPP IM client, you should use HTTP File Upload because that works asynchronously and works better with multiple devices. [Kaidan](https://www.kaidan.im/) for example uses it with QXmpp.
> 
> Just out of interest: What kind of project are you trying to build with QXmpp?



I want make a IM client with Qt on Android,I used iris and gloox before,they can trans fire any environment,but the api is not easy to use,so i try  qxmpp,the qxmpp file transfer error is ‘QXmppTransferJob::ProtocolError’ and ‘<error type=\"cancel\" code=\"404\"><item-not-found xmlns=\"urn:ietf:params:xml:ns:xmpp-stanzas\"/></error>’ on Android to Android，Android to Windows no problem,windows to Android no problem too.I try the android to android in the same wifi，later i try they in the different network using LTE and the other WiFi，but not success！

There is another problem：the receive file on Android must be flush the buffer  can save right，your can check it。
Thanks

**Comment by lnjX** [comment]
If you really want to create a modern XMPP client, that should work well with other modern clients, you won't get around HTTP File Upload (QXmppHttpUploadRequestManager). Also you should think about whether you really need a new client. You could join an existing project, like Kaidan which also uses QXmpp and Qt for Android.
&lt;advertisement&gt;Just in case you're interested, I'd be happy to welcome you there. :)&lt;/advertisement&gt;

I haven't used Jingle File Transfer on my own, so I'm probably not the best person to ask about this issue. However, could you still provide a more detailed XML log of the error? Only `<error type="cancel" code="404">` doesn't help.

**Comment by lnjX** [comment]
I'll close this due to inactivity.
