### ISSUE TITLE
Omemo encryption

### ISSUE THREAD

**Issue by niqt** [qxmpp-project/qxmpp#306]
Hi,
there is some plan about the omemo encryption? I'd like collaborate on it

**Comment by lnjX** [comment]
Hi @niqt, thanks for your interest.
OMEMO support has already its own issue (#133), so let's use the original issue.

OMEMO requires PubSub/PEP and (the newest specifications) also require Stanza Content Encryption. Fortunately I'm currently already working on PubSub and PEP. OMEMO is also an issue for us ([Kaidan](https://invent.kde.org/network/kaidan/) developers) and we'd be happy if you could help us with that. Stanza Content Encryption would be very important before you can start with OMEMO probably, so if you're interested in that, that would be great. :)

Out of personal interest: What's your background / how do you want to use QXmpp and OMEMO?

**Comment by niqt** [comment]
I use Qt from 0.6 version. In this moment the chat word has an hype. I already deceloped mobile application (native) so i'd like to use also opensource things. You can see in my github profile something about my past contribution in opensource, other things are not in github.

**Comment by niqt** [comment]
I can work also kaidan iOS version.

**Comment by lnjX** [comment]
> I use Qt from 0.6 version

Woah :)

> I can work also kaidan iOS version.

That would be **really** cool! We're all not very familiar with iOS (or generally Apple) development, so that would be a huge help! :)
