### ISSUE TITLE
 can't open the file 'libqxmpp.dll.lib'.

### ISSUE THREAD

**Issue by MosterKU** [qxmpp-project/qxmpp#307]
I can't add the library to my Qt project when running, I can't open the file 'libqxmpp.dll.lib'.

please someone help me

**Comment by lnjX** [comment]
I'm not experienced with building on windows, but doesn't the name need to end on `.dll` (instead of `.dll.lib`)?

**Comment by MosterKU** [comment]
thanks, in the end the problem was that I was compiling with msvc and it was with mingw I didn't know what mattered what compiler type I used

**Comment by lnjX** [comment]
OK
