### ISSUE TITLE
Xmpp Message read notification

### ISSUE THREAD

**Issue by vampiebar** [qxmpp-project/qxmpp#310]
Is there any messaging event? for reading message and send to other client that your message is delivered and read?

Thanks..

**Comment by lnjX** [comment]
There're multiple ways of doing that:
 1. [XEP-0184: Message Delivery Receipts](https://xmpp.org/extensions/xep-0184.html):
Includes a receipt request in each message and when another client supporting this extension receives it, it will reply with a message receipt.
You need to set `isReceiptRequested` to true of your `QXmppMessage` (using [`QXmppMessage::setReceiptRequested`](https://doc.qxmpp.org/qxmpp-1/classQXmppMessage.html#a7ea77ae7738907a21a41d4dc3da767a6)).
Then you can use the [`QXmppMessageReceiptManager`](https://doc.qxmpp.org/qxmpp-1/classQXmppMessageReceiptManager.html) to handle incoming receipts for your message.

 1. [XEP-0333: Chat Markers](https://xmpp.org/extensions/xep-0333.html):
Uses markers that are sent till which message a conversation has been received or displayed.
The problem with this is just that some messages may be "lost".
You can directly read and set the correct markers from incoming and outgoing QXmppMessages.

I hope I could help you.
