### ISSUE TITLE
Offline message retrival

### ISSUE THREAD

**Issue by vampiebar** [qxmpp-project/qxmpp#311]
Hello,
I am sending offline message to Adium client from qxmpp and Adium is getting when user is online.
Is there a way in qxmpp to get offline messages when user logged in?
Thanks.

**Comment by lnjX** [comment]
You can use one of:
1. [XEP-0313: Message Archive Management](https://xmpp.org/extensions/xep-0313.html): [`QXmppMamManager`](https://doc.qxmpp.org/qxmpp-1/classQXmppMamManager.html)
1. [XEP-0136: Message Archiving](https://xmpp.org/extensions/xep-0136.html): [`QXmppArchiveManager`](https://doc.qxmpp.org/qxmpp-1/classQXmppArchiveManager.html) (not recommended, the XEP is deprecated)
