### ISSUE TITLE
QXmpp client failed to connect to the local host

### ISSUE THREAD

**Issue by faizol** [qxmpp-project/qxmpp#316]
Hi,
 I just setup my environment to use SSL certificates generated using mkcert (https://github.com/FiloSottile/mkcert). I also setup local DNS service with proper A and SRV records to map xmpp services to the local pc. Then I ran a test to make sure that the certificates are OK using openssl command;
`openssl s_client -starttls xmpp -connect xmpp.domain.test:5222`, 
and got output confirming that the connection is OK using TLSv1.3 protocol.

However when I tried to connect to the server using QXmppConfiguration setHost("xmpp"), the client just keep on reconnecting to the server and didn't receive any confirmation of an accepted connection. How should I go about to solve this connection problem?

TIA,

Best regards,

**Comment by lnjX** [comment]
Hey,
you also need to set a port, when you select a custom host.

**Comment by faizol** [comment]
Hi,
Thank you for the reply. My setup is behind a proxy, so what I did to solve this was to disable the proxy in application (`setType(QNetworkProxy::NoProxy)`), and now I can properly connect to the server. 

Thank you.
Best regards,
