### ISSUE TITLE
Is it compilable with Qt6 now?

### ISSUE THREAD

**Issue by faizol** [qxmpp-project/qxmpp#318]
Hi,

I was checking CMakeLists.txt and noticed that;

```
# prefer Qt6
find_package(Qt6 QUIET COMPONENTS Core Network Xml)
if(NOT Qt6_FOUND)
    find_package(Qt5 5.7.0 REQUIRED COMPONENTS Core Network Xml)
endif()
```

Is the library compilable with Qt6 beta 1 now? Also, is it possible to bump the CMake version from 3.3 to something > 3.10? Cmake tries to use legacy opengl library on Linux if the version is less than 3.10.

Thanks.

**Comment by lnjX** [comment]
> Is the library compilable with Qt6 beta 1 now?

Yes, it is.

> Also, is it possible to bump the CMake version from 3.3 to something > 3.10? Cmake tries to use legacy opengl library on Linux if the version is less than 3.10.

If cmake 3.10 is available everywhere (where QXmpp is currently supported, meaning ubuntu 18.04, i think).

**Comment by faizol** [comment]
Thank you :+1:
