### ISSUE TITLE
SCRAM-SHA-512(-PLUS) + SCRAM-SHA3-512(-PLUS)

### ISSUE THREAD

**Issue by Neustradamus** [qxmpp-project/qxmpp#319]
Good news after SCRAM-SHA-1(-PLUS)/SCRAM-SHA-256(-PLUS), there are:

SCRAM-SHA-512(-PLUS):
- https://tools.ietf.org/html/draft-melnikov-scram-sha-512

SCRAM-SHA3-512(-PLUS):
- https://tools.ietf.org/html/draft-melnikov-scram-sha3-512

**Comment by lnjX** [comment]
I currently don't plan to implement this, feel free to open a PR.

**Comment by Neustradamus** [comment]
@lnjX: This ticket is not solved, can you reopen it?
Thanks in advance.

**Comment by JBBgameich** [comment]
It's not mandatory for project maintainers to accept feature requests. Unless you are planning to implement this feature, please accept that it is currently not on the roadmap.

**Comment by Neustradamus** [comment]
@JBBgameich: Close a ticket = problem solved but it is not.

If you do not want to solve it, please keep a ticket opened, people will contribute.

**Comment by Neustradamus** [comment]
@lnjX: Thanks a lot for https://github.com/qxmpp-project/qxmpp/pull/320.
