### ISSUE TITLE
XEPs and RFCs support page with VERSION

### ISSUE THREAD

**Issue by Neustradamus** [qxmpp-project/qxmpp#323]
It is possible to have a XEPs and RFCs support page with VERSION (XEP-XXXX v1.2), it is not complete at the moment and no RFCs list file:
- https://github.com/qxmpp-project/qxmpp/blob/master/doc/xep.doc
- https://doc.qxmpp.org/qxmpp-1/xep.html

Examples:
- https://github.com/UWPX/UWPX-Client/blob/master/README.md
- https://github.com/telldus/xmppjs-client-plugins/blob/master/README.md
- https://github.com/ortuman/jackal/blob/master/README.md
- https://profanity-im.github.io/xeps.html
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

Linked to:
- https://github.com/qxmpp-project/qxmpp/issues/138

**Comment by lnjX** [comment]
Feel free to actually help and submit a pull-request. :)

Unfortunately there's currently no plan to work on this.

**Comment by Neustradamus** [comment]
It is not good to close an unsolved ticket.
