### ISSUE TITLE
Can't retrieve archive information.

### ISSUE THREAD

**Issue by vityafx** [qxmpp-project/qxmpp#33]
Can xmpp server not to store archives?
When I try to repeat archiveHandling_7 example in my project I see in log the following:

    сб янв. 24 11:42:23 2015 SENT <iq id="qxmpp49" type="get"><retrieve xmlns="urn:xmpp:archive" with="mastermind@xmpp.quakelive.com"
    сб янв. 24 11:42:23 2015 RECEIVED <iq type="error" id="qxmpp49" to="fx@xmpp.quakelive.com/QXmpp"><retrieve xmlns="urn:xmpp:archive" with="mastermind@xmpp.quakelive.com" start="2015-01-10T08:42:23.561Z"/><error code="503" type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>

Does that mean that xmpp server refuses to give me archive or `archiveHandling` example can be modified to fix the problem?

**Comment by jlaine** [comment]
Your server does not support archiving, what server is it?

**Comment by vityafx** [comment]
As you can see, it is quakelive's internal xmpp chat: `xmpp.quakelive.com`.
Okay then, I've thought it was my problem. Thank you for the response.
