### ISSUE TITLE
How to add QXMPP library in Qt5

### ISSUE THREAD

**Issue by RHamidR** [qxmpp-project/qxmpp#34]
I am a (dot)net programmer and this is my first time to develop a real application in Qt and C++. So i am confused and very disappear in using an Qt based XMPP protocol in Qt5 for mobile (android and etc).

Can somebody help me and [others like me and] complete these tutorial and documentations by Step-By-Step guide to adding this QXMPP library and start programming by it's APIs.

Thanks in advance.

**Comment by jlaine** [comment]
As stated in the readme, basic knowledge of c++/qt is a prerequisite, we do not have the manpower to teach you how to do this. You can try your luck on the Qxmpp discussion group though.
