### ISSUE TITLE
Implement filtered notification for PEP node?

### ISSUE THREAD

**Issue by GoodOldGamer** [qxmpp-project/qxmpp#345]
I'm trying to register to a PEP node. This should be done via filtered notifications (XEP-0115: Entity Capabilities).

To achieve this, I created a QXmppClientExtension to handle the PubSub-events for this PEP node. The extension returns in discoveryFeatures() two strings:
nodename
nodename+notify

This works fine so far, the two entries are added to the client capabilities.
But the client doesn't get informed when the other user make changes to this PEP node, only when it has changed its own.

Server is Openfire 4.6.2 and the roster is created via group contact list sharing, so that each user of the group is subscribed to the presence of each other user in the group.

PEP in general is working with this server. When I connect with e.g. Pidgin I also get log entries like "Entity 'user@server' expressed new interest in receiving notifications for nodes ...". I do not get such log entries when connecting via my QXmpp-client.

So I guess I'm doing something wrong?

**Comment by lnjX** [comment]
So the problem is that the notifications for the user's own node work, but not from other users. Have you double checked that there is a roster subscription from both sides? (it could be possible that the users are in the roster without subscriptions)

Otherwise, I'm sorry, I've got no idea since the other notifications already work.

**Comment by GoodOldGamer** [comment]
Yes, all user have presence subscription set to both for all entries in their roster.
And it's working when I explicitly subscribe to the node for each user in the roster via pubsub subscribe iq.

So it seems that either the PEP auto-subscribe feature or filtered notifications isn't working as expected. And when the way I implemented it isn't wrong, I guess the problem lies somewhere in Openfire. Maybe the node configuration? I guess if no configuration is delivered with the publish iq, the server uses a server side default config?

**Comment by lnjX** [comment]
PEP notifications work fine, eg see OmemoManager. I guess the problem here wasn't caused by QXmpp. If you find anything wrong in QXmpp related to PEP, feel free to reopen.
