### ISSUE TITLE
Access Violation in QXmppMessage::toXml(QXmlStreamWriter *)

### ISSUE THREAD

**Issue by servonic** [qxmpp-project/qxmpp#35]
When passing an QXmlStreamWriter to the function QXmppMessage::toXml(QXmlStreamWriter *) that was constructed with this constructor
````C++
QXmlStreamWriter::QXmlStreamWriter(QString * string)
````
and the message has xhtml content this line causes an A/V as xmlWriter->device() returns a nullptr.
````C++
xmlWriter->device()->write(d->xhtml.toUtf8());
````

I haven't seen a test case for toXml. Is it better to add a new testcase for toXml that or just add a call to toXml to the existing test case function testXhtml()?

**Comment by jlaine** [comment]
Hm, it is indeed a bit odd that ::toXml is accessing xmlwriter->device(), but I am not sure there is a better way.

Concerning the unit tests : toXml is being exercised by every test in tests/qxmppmessage/tst_qxmppmessage.cpp, see:

template <class T>
static void serializePacket(T &packet, const QByteArray &xml)
{
    QBuffer buffer;
    buffer.open(QIODevice::ReadWrite);
    QXmlStreamWriter writer(&buffer);
    packet.toXml(&writer);
    qDebug() << "expect " << xml;
    qDebug() << "writing" << buffer.data();
    QCOMPARE(buffer.data(), xml);
}

**Comment by jlaine** [comment]
Why exactly are you using .toXml() yourself? This method is not documented as it is internal.

Also, if you absolutely must call .toXml, you can pass it a writer created with QXmlStreamWriter(QByteArray &ba), this will work just fine.

**Comment by servonic** [comment]
I'm using qxmpp for creating a server. I need to get a (xml) string representation of the stanza in order to store offline messages.
Additionally, I call QXmppPresence ::toXml() for storing (un)subsription requests and unavailable presences.

**Comment by jlaine** [comment]
As stated above, if you *must* use toXml(), pass it a QXmlStreamWriter constructed on a QByteArray. You can then convert that QByteArray to a QString if you need to.
