### ISSUE TITLE
QXmppOutgoingClient doesn't recognize "bad-auth" auth failure replies

### ISSUE THREAD

**Issue by 0xd34df00d** [qxmpp-project/qxmpp#36]
Some servers (like xmpp.yandex.ru, see original bugreport http://dev.leechcraft.org/issues/1865 (in russian)) don't send `not-authorized` as a result of incorrect auth parameters, sending `bad-auth` instead.

This should probably be handled on QXmpp side than on client library user side, emitting proper error condition, as QXmpp has more context information.

**Comment by jlaine** [comment]
I am not too happy with this commit, now users of the library need to check both NotAuthorized and BadAuth (not standard) to check whether there was an authentication issue. I don't mind adding some level of support for buggy servers, but at least remap the error to something that exists in the standards.

Also: make it apparent in the code that this is a workaround for a server issue.

**Comment by 0xd34df00d** [comment]
Ok, I gave this thought a few more days to think about it and tend to agree
with you now: I cannot imagine of a use case where BadAuth and
NotAuthorized should actually be distinguished. Will change this in the few
coming days when I'll get my hands on it.

**Comment by jlaine** [comment]
Hi Georg, I have commited an alternate way of handling the "bad-auth" error condition, let me know if it works for you.

**Comment by 0xd34df00d** [comment]
Hi Jeremy,

Yeah, judging from the commit, that should work just fine. Thanks!
