### ISSUE TITLE
It is working well on Windows but have no affect on Android apps!!!!!!

### ISSUE THREAD

**Issue by RHamidR** [qxmpp-project/qxmpp#39]
I've tried to write simple app to find out if it connects to server. It connects on Windows well. Then I've tried to test it on Android, but it doesn't connect and I don't know why because it shows no error.

The app running correctly on Android, but it seems nothing is going on about XMPP protocol. No connection and logging. All I got in debug() just this one line that repeats 3 or 4 times:

    D/libc-netbsd(  465): getaddrinfo: gmail.com get result from proxy >>

This is my first try:

    lbl.setText("is not Connected");
    client.connectToServer("hami....@gmail.com", "asdasd");
    while(!(client.isConnected())){
        a.processEvents();
    }
    lbl.setText("Connected");

it does connect but just on Windows. I've tried the GuiClient project, both of them seems not working.
I changed this line

    DEFINES +=  QXMPP_LIBRARY_TYPE=staticlib
to

    DEFINES +=  QXMPP_LIBRARY_TYPE=shared

and build libqxmpp.so but nothing again.
I wrote these lines in my application's .pro file for adding library to my project.

    CONFIG(debug, debug|release) {
        win32{
            QXMPP_LIBRARY_NAME_INC = qxmpp_d0
        } else {
            QXMPP_LIBRARY_NAME_INC = qxmpp_d
        }
    }else{
        win32{
            QXMPP_LIBRARY_NAME_INC = qxmpp0
        }else{
            QXMPP_LIBRARY_NAME_INC = qxmpp
        }
    }
    LIBS += -L./qxmpp/src -l$$QXMPP_LIBRARY_NAME_INC

I looked in the lib directory of my projects installed APK file and there was no libqxmpp.so flile or any related...
i modified the APK file and added the libqxmpp.so file myself and signing the app by step by step guide of this link and installed the modified APK file on phone, And Nothing again.

Thanks in advance.

**Comment by RHamidR** [comment]
When the connect method called, this is the last log in Application Outputs 

	D/libc-netbsd(  465): getaddrinfo: gmail.com get result from proxy >>

and repeat it for 3 or 4 times and nothing....

I looked in the lib directory of my projects installed APK file and there was no libqxmpp.so flile or any related...
i modified the APK file and added the "libqxmpp.SO" file myself and signing the app by step by step guide of this [link](http://scn.sap.com/community/gateway/blog/2014/05/21/how-to-modify-an-apk-file) and installed the modified APK file on phone, And Nothing again...


Dear @jlaine , Do you have any advice to me.
Please somebody help me. If someone help me to get it work on android, I promise to don't ask any question again here.
Please just somebody help me to get it work on android. I need it as my life.

**Comment by RHamidR** [comment]
Is it something wrong with my code or QXmpp?
Does anyone here have an answer for me? Please. I was waited for long time.

**Comment by jlaine** [comment]
Your code looks very weird, why are you manually calling processEvents instead of just using the event loop?

**Comment by jlaine** [comment]
The problem described here seems to be an Android deployment, not specific to QXmpp.
