### ISSUE TITLE
setIgnoreSSLErrors makes no difference

### ISSUE THREAD

**Issue by ksiazkowicz** [qxmpp-project/qxmpp#42]
I wanted to add a feature to ignore SSL errors during connection (sometimes certificate is messed up on the server but you still want to connect).

I used xmppConfig.setIgnoreSslErrors(true), where xmppConfig is an object of QXmppConfiguration class I give QXmppClient when calling connectToServer(QXmppConfiguration);

For some reason, my app still fails when SSL error occurs. Is it something wrong with QXmpp or my code? I'm using qxmpp 0.8.0.

**Comment by jlaine** [comment]
Can you please post the minimal amount of code to reproduce the issue?

**Comment by ksiazkowicz** [comment]
To reproduce the issue you need an old version of Qt (for example 4.7).

https://github.com/ksiazkowicz/lightbulb/blob/fluorescent/src/xmpp/MyXmppClient.cpp#L92

**Comment by jlaine** [comment]
Can you please post the log of XMPP messages + any errors?

**Comment by jlaine** [comment]
No feedback in over a year, closing
