### ISSUE TITLE
Can't create a MUC room on my local server server

### ISSUE THREAD

**Issue by gakwaya** [qxmpp-project/qxmpp#45]
I need to compose a stanza like this (to create the coven room on the chat.shakespeare.lit server)

```xml
<presence
    from='hag66@shakespeare.lit/pda'
    id='n13mt3l'
    to='coven@chat.shakespeare.lit/thirdwitch'>
  <x xmlns='http://jabber.org/protocol/muc'/>
</presence>

```

to the server but cant find a way to compose it into a packet and send it to my server.I have tried

```C++
 QXmppMucManager *manager = new QXmppMucManager;
    m_xmppClient.addExtension(manager);
QXmppMucRoom *room = manager->addRoom("createdRoom1@conference.danil-pc");
    room->setNickName("whoAreYou");
    room->join();

```

but the program crashes as soon as the addRoom function is called.Messing with different configurations for the QXmppPresesence didn't help much either.Is there a way one can send this directed presence stanza I am not finding. Also does this library offer a way to construct a stanza yourself through xml streams so I can build it myself?Thanks.

**Comment by jlaine** [comment]
If you expect help, please at least reply to the questions I sent when you wrote to the mailing list.

**Comment by gakwaya** [comment]
Sorry but I didn't get notified of your replies.I just checked the spam folder and still nothing!Is there a public link to the mailing list logs so I can look there?Thanks for your time.

**Comment by gakwaya** [comment]
In case somebody has the same issues ,I was able to create the rooms.Here is the code that does that.I create and configure the room on the fly(I am using Openfire and it allows it) but you can request the configuration form if you want.

         QString jid=roomName.text()+"@conference."+serverName;
           if(jid.isEmpty())
                   return ;
               QList<QXmppMucRoom*> rooms = manager->rooms();
               QXmppMucRoom* r;
               foreach(r, rooms)
               {
                   if(r->jid() == jid)
                   {
                       //LOG_MODEL_DEBUG("Group chat", "had joined room[%s]", qPrintable(jid));
                       return ;
                   }
               }
               m_pRoom = manager->addRoom(jid);
               if(m_pRoom)
               {
                   //nick
                   m_pRoom->setNickName("theDip");
                   //join the room.
                   m_pRoom->join();
               }

               //Prepare the dataform.
               QXmppDataForm form(QXmppDataForm::Submit);
               QList<QXmppDataForm::Field> fields;
               {
                   QXmppDataForm::Field field(QXmppDataForm::Field::HiddenField);
                   field.setKey("FORM_TYPE");
                   field.setValue("http://jabber.org/protocol/muc#roomconfig");
                   fields.append(field);
               }
               QXmppDataForm::Field field;
               field.setKey("muc#roomconfig_roomname");
               field.setValue(roomName.text());
               fields.append(field);

               field.setKey("muc#roomconfig_subject");
               field.setValue(roomSubject.text());
               fields.append(field);

               field.setKey("muc#roomconfig_roomdesc");
               field.setValue(roomDesc.text());
               fields.append(field);
               {
                   QXmppDataForm::Field field(QXmppDataForm::Field::BooleanField);
                   field.setKey("muc#roomconfig_persistentroom");
                   field.setValue(true);
                   fields.append(field);
               }

               form.setFields(fields);
               //The dataform ends here.
               m_pRoom->setConfiguration(form);
