### ISSUE TITLE
How do I install QXMPP lib on windows 8?

### ISSUE THREAD

**Issue by Luis-Abreu** [qxmpp-project/qxmpp#46]
I have a QT project in which I want to include the QXMPP library. I added it as a dynamic external library but it still doesn't recognize the header files from QXMPP

"Cannot open include file: 'QXmppClient.h': No such file or directory"

**Comment by gakwaya** [comment]
You probably need to add includes pointing to the location of your QXmpp headers:Something like this:
INCLUDEPATH += H:\chatProject\src\base
INCLUDEPATH += H:\chatProject\src\client

**Comment by Luis-Abreu** [comment]
I did that but now im having this error;
"C:\Users\User\Documents\QT\XmppClient\base\qdnslookup_symbian.cpp:48: error: C1083: Cannot open include file: 'dns_qry.h': No such file or directory"

"C:\Users\User\Documents\QT\XmppClient\base\qdnslookup_unix.cpp:50: error: C1083: Cannot open include file: 'netinet/in.h': No such file or directory"

**Comment by gakwaya** [comment]
You need to tell your compiler where to find those files such as dns_qry.h . Try searching your file system for  dns_qry.h and just add the location of those files using another INCLUDEPATH statement in your .pro file.

**Comment by Luis-Abreu** [comment]
I can't find it in my system :/

**Comment by gakwaya** [comment]
looking at the QXmpp sources these files are included from here:
 else:symbian:SOURCES += base/qdnslookup_symbian.cpp
    else:unix:SOURCES += base/qdnslookup_unix.cpp

in the base.pri file. A silly question: how did you use QXmpp in your application.Personally I first compile QXmpp for my target platform( have tested already on Desktop( mingw /msvc) and android,and then load the generated libraries in my projects through the LIB statement in my .pro file.Are you doing the same?

**Comment by Luis-Abreu** [comment]
I just deleted the qdnslookup_symbian.cpp and compiled on a ubuntu machine and now i dont have any errors. I tried adding the library using the LIB statement but it didnt find the headers anyway. So I just putted all the files in my src folder.
