### ISSUE TITLE
unable to transfer large file from windows to ios

### ISSUE THREAD

**Issue by veeru22164141** [qxmpp-project/qxmpp#473]
we are developing application for meeting and presentation, my xmpp server is running on device having attached display system . clients (like windows application , ios application and android application ) communicating via xmpp server . exchanging text message and sending small file  is running properly. But when we send large file(above 90mb) from windows to ios ,it get failed and throws file protocol error.  this sample yml file which we use on server side.
[ejabberdyml.txt](https://github.com/qxmpp-project/qxmpp/files/9654661/ejabberdyml.txt)

**Comment by lnjX** [comment]
Sorry, but I don't think I can help you without a proper error message (or steps to reproduce).

**Comment by lnjX** [comment]
You can use HTTP File Uploading with the QXmppHttpUploadManager (or soon also with the QXmppFileSharingManager).
