### ISSUE TITLE
Document new file upload methods

### ISSUE THREAD

**Issue by melvo** [qxmpp-project/qxmpp#496]
@lnjX @JBBgameich It would be great if you could document the new methods mentioned in https://github.com/qxmpp-project/qxmpp/actions/runs/3173694931/jobs/5169592864#step:6:44 and subsequent lines.

**Comment by lnjX** [comment]
There're no issue on master.

**Comment by lnjX** [comment]
Hmm okay there're warning on the CI, but not when I run doxygen locally.

**Comment by lnjX** [comment]
![image](https://user-images.githubusercontent.com/13557034/195622597-69090078-1900-4f38-b811-e518256abc80.png)
![image](https://user-images.githubusercontent.com/13557034/195622685-4d634745-4ceb-49bc-b787-4585b23060e1.png)

This seems to be a doxygen bug. I'm using doxygen 1.9.4, the CI is probably using the latest version from ubuntu, so 1.9.1.
