### ISSUE TITLE
 Creating pubsub (xep 0060) nodes from QXmpp

### ISSUE THREAD

**Issue by gakwaya** [qxmpp-project/qxmpp#50]
Does Qxmpp allow the creation of pubsub nodes or I have to create the stanzas myself. I have seen the QXmppPubSubIq but I have found no way i could use it to build a stanza like this:

           <iq from="queen@wonderland.lit/throne"
            id="cr561nd0"
            to="notify.wonderland.lit"
            type="set">
            <pubsub xmlns="http://jabber.org/protocol/pubsub">
            <create node="queenly_proclamations"/>
            </pubsub>
            </iq>

My thoughts were that there should be an CreateQuery enum in the QXmppPubSubIq class like

          class QXMPP_EXPORT QXmppPubSubIq : public QXmppIq
          {
          public:
              /// This enum is used to describe a publish-subscribe query type.
     enum QueryType
    {
        AffiliationsQuery,
        DefaultQuery,
                  CreateQuery//This is not present. 

And setting the queryType on the stanza would create a stanza to create a pubsub node on the server. Is a thing like present in QXmpp or am I missing something.

Thank you for your time.

**Comment by jlaine** [comment]
At the moment pubsub is not supported in QXmpp for lack of manpower. The QXmppPubSubIq class that is in the code was the start of a development which never got completed. If you have some spare time, feel free to submit a pull request (make sure you include unit tests in your PR)
