### ISSUE TITLE
CMake build: add potentially missing dependencies in "Building QXMPP" section

### ISSUE THREAD

**Issue by taiBsu** [qxmpp-project/qxmpp#508]
I'd like to propose to add the line `sudo apt install libgl-dev` to the README file for compatibility reasons above this line here:
https://github.com/qxmpp-project/qxmpp/blob/cbf32098d46b12b69b5ed5f491127023093374e4/README.md?plain=1#L63
It will fix the CMake error `Failed to find "GL/gl.h" in "/usr/include/libdrm"` when libgl is not installed.

**Comment by lnjX** [comment]
This should be a dependency of Qt. QXmpp does not depend on it. Also, we can't use distro-specific commands in the README.
