### ISSUE TITLE
timestamp problem about QXmppMessage

### ISSUE THREAD

**Issue by LightZam** [qxmpp-project/qxmpp#52]
There is a problem for me using QXmppMessage
the mthod QXmppMessage::parse, will using  XEP-0091: Legacy Delayed Delivery in the end.

because the order of code, legacy will replace XEP-0203 : Delayed Delivery's value

below code is the xml example, i have no chance to get timestamp with millisecond because of d->stamp will use the legacy delayed delivery.

XEP-0091 is not recommended now, can the XEP-0203 parse code move to below XEP-0091, then it will
replace XEP-0091's timestamp if there is XEP-203

if you agree with this, maybe i can make a pull request

	<message type="groupchat" from="crd_cii@groupchat.im.gss.com.tw" to="zam_huang@im.gss.com.tw/QXmpp">
		<subject>CRD_CII</subject>
		<delay xmlns="urn:xmpp:delay" stamp="2014-11-13T06:57:41.509Z" from="crd_cii@groupchat.im.gss.com.tw"/>
		<x xmlns="jabber:x:delay" stamp="20141113T06:57:41" from="crd_cii@groupchat.im.gss.com.tw"/>
	</message>

**Comment by jlaine** [comment]
OK, this is a valid point, I agree with using the most recent standard foremost, and only falling back to XEP-0091

**Comment by jlaine** [comment]
Closed in #53
