### ISSUE TITLE
How to check if a QXmppMessage has the delay element attached?

### ISSUE THREAD

**Issue by timakas** [qxmpp-project/qxmpp#527]
I am trying to determine if an incoming message is a delayed offline message.

I've read that QXmpp supports XEP - 0203 Delayed Delivery, and I have gone through the QXmpp documentation, but I can't seem to find a way to check if a QXmppMessage has the delay element attached. Can someone please offer a solution to check for the delay element? Appreciate any help, thanks.

**Comment by melvo** [comment]
https://doc.qxmpp.org/qxmpp-1/classQXmppMessage.html#a455a05e7adee6a989e1e56f1a1766373 (`QXmppMessage::stamp()`) is what you are looking for :)

**Comment by timakas** [comment]
> https://doc.qxmpp.org/qxmpp-1/classQXmppMessage.html#a455a05e7adee6a989e1e56f1a1766373 (`QXmppMessage::stamp()`) is what you are looking for :)

Thanks :) I'm still a bit new to working with QXmpp. So could I ask about the implementation of checking for the delay message? Would it work like this... Upon connecting to the server I set a login time variable, and when delay messages come from the server I compare the message stamp to the login time variable, and if the message stamp is older than the login time, then this confirms it is a delay message?

**Comment by lnjX** [comment]
@timakas If the message did not contain a delay element, `QXmppMessage::stamp().isNull()` will return true.
