### ISSUE TITLE
Broken discovery manager

### ISSUE THREAD

**Issue by TheBluestBird** [qxmpp-project/qxmpp#529]
I'm so sorry but that abstract template clever horror starting from the line 310 of a [this file](https://github.com/qxmpp-project/qxmpp/blob/master/src/client/QXmppDiscoveryManager.cpp) just doesn't work! Every time qxmpp receives absolutely valid discovery Iq it just replies that this feature is not implemented yet.
I tried to debug it, but my debugger just skips that second template method of this abstraction matrioshka

**Comment by lnjX** [comment]
Thanks for testing!
