### ISSUE TITLE
Enable parallel installation of Qt5 and Qt6 version

### ISSUE THREAD

**Issue by plata** [qxmpp-project/qxmpp#540]
see https://invent.kde.org/sysadmin/ci-images/-/merge_requests/107

**Comment by topazus** [comment]
@lnjX I try to make qxmpp rpm package on Fedora. I have a question here. Which sub-package can these following files go into, qxmpp-qt5-devel or qxmpp-qt6-devel?
```
/usr/lib64/cmake/QXmpp/QXmppConfig.cmake
/usr/lib64/cmake/QXmpp/QXmppConfigVersion.cmake
/usr/lib64/pkgconfig/qxmpp.pc
```
spec file: https://gist.githubusercontent.com/topazus/40e564f2709980e1cd6591474ab68811/raw/236d7923a5f68b44ff277e3a15cb272b5019b58e/qxmpp.spec

**Comment by lnjX** [comment]
@topazus The files are needed in both versions (qt 5/6), so users can just use `find_package(QXmpp)` (without explicitly setting the major version).
I already received complaints about this from opensuse about this approach though, so not sure this is ideal, but users of QXmpp don't need to change anything in their CMakeLists.txt this way.
I think the opensuse maintainer needed to create an extra package `qxmpp-compat` (or something like that) for the files :/
