### ISSUE TITLE
iOS on Qt 5.4.1

### ISSUE THREAD

**Issue by antofik** [qxmpp-project/qxmpp#55]
Does not compile for iOS with Qt 5.4.1 with several errors like "member access into incomplete type 'QSslSocket' QXmppStream.cpp 92", and so on at every line, where method of socket are used.

I've used newly installed Qt 5.4.1 for Mac OS X (via online installer), and clean clone of qxmpp repository. Then I open qxmpp project in Qt Creator, press "Build", and got this errors

**Comment by jlaine** [comment]
Qt 5.4 for iOS does not have SSL support, so it will not work. You can try with Qt 5.5 beta, I contributed SSL support for iOS.
