### ISSUE TITLE
RetractQuery bug

### ISSUE THREAD

**Issue by LightZam** [qxmpp-project/qxmpp#56]
according to http://xmpp.org/extensions/xep-0060.html#publisher-delete
and http://xmpp.org/extensions/xep-0060.html#owner-delete

the retract query should contain an item which going to be delete

    <iq type='set'
    from='hamlet@denmark.lit/elsinore'
    to='pubsub.shakespeare.lit'
    id='retract1'>
        <pubsub xmlns='http://jabber.org/protocol/pubsub'>
            <retract node='princely_musings'>
                <item id='ae890ac52d0df67ed7cfdf51b644e901'/>
            </retract>
        </pubsub>
    </iq>
      
but 0.8.3 version do it this way

    <iq type='set'
    from='hamlet@denmark.lit/elsinore'
    to='pubsub.shakespeare.lit'
    id='retract1'>
        <pubsub xmlns='http://jabber.org/protocol/pubsub'>
            <retract node='princely_musings'/>
        </pubsub>
    </iq>

it probably make a mistake between 8.4 Delete Node and 7.2 Delete an Item From Node

    <iq type='set'
    from='hamlet@denmark.lit/elsinore'
    to='pubsub.shakespeare.lit'
    id='delete1'>
        <pubsub xmlns='http://jabber.org/protocol/pubsub#owner'>
            <delete node='princely_musings'/>
        </pubsub>
    </iq>

if you agree with my opinion, i will fix it and make a pull request.

**Comment by jlaine** [comment]
Go ahead, and please provide a unit test

**Comment by jlaine** [comment]
Fixed in f2f506807bdd41795acaddc80430025fb9a62a7b
