### ISSUE TITLE
Link error and QXMPP cannot be used

### ISSUE THREAD

**Issue by yezhening** [qxmpp-project/qxmpp#564]
Hello !

I have a link error while executing the command："cmake --build ."

Here is my environment：
- Windows10
- x64
- Visual Studio 2019
- Qt 5.14.2
- QXMPP stable branch‘s files
- CMake 3.25.1
- And there is no openssl、sasl、zlib、libidn and QCA library

Here is my error messages：
[
![截图20230320112255](https://user-images.githubusercontent.com/85481132/226239273-4644810b-2a23-4c72-8c97-733cdc644809.png)
](url)
[
![截图20230320113000](https://user-images.githubusercontent.com/85481132/226240077-6dee9617-5f93-48fb-9b5f-baf182f93708.png)
](url)

【Here is my some questions：】
1. How can I fix these mistakes？Do I need to install any other dependency libraries in advance？
2. The README file description is not detailed enough. There are too few online materials. Could you provide more detailed tutorials？（Especially in Windows）

I hope the problem can be seen, answered and solved effectively. Thank you！

**Comment by JBBgameich** [comment]
Hi, can you post the full command output of `cmake --build .`?
It would be interesting to see if this is the only error, or if it fails to link Qt in general.
It would also be useful to have a log in english, because currently I have to guess what the errors mean :D

**Comment by JBBgameich** [comment]
Ah that makes sense. It previously looked like it was not linking against Qt, but it was just linking against Qt built by an incompatible compiler.
