### ISSUE TITLE
no support about managing discussion history

### ISSUE THREAD

**Issue by LightZam** [qxmpp-project/qxmpp#57]
there is no support about managing discussion history : http://xmpp.org/extensions/xep-0045.html#enter-managehistory, but it will be needed in mobile device.

###according to protocol description
	
A user might want to manage the amount of discussion history provided on entering a room (perhaps because the user is on a low-bandwidth connection or is using a small-footprint client). This is accomplished by including a <history/> child in the initial presence stanza sent when joining the room.

there is a reason to implement it

if you agree with my opinion, i will implement it and make a pull request

**Comment by jlaine** [comment]
Do you have any idea what server support looks like?

My only concern here is that we are going to add yet more methods to QXmppPresence

**Comment by LightZam** [comment]
i am not sure your server support meaning, 
does it means that how server side dealing with this presence?
or you just want to know how i am going to implement it?

**Comment by jlaine** [comment]
Sorry if I was not clear, I mean : do servers actually implement attributes defined in "7.2.15 Managing Discussion History"

**Comment by 0xd34df00d** [comment]
Prosody does if I'm not mistaken. And, moreover, it's a chicken-egg problem
:)

Jeremy, I'm not sure it does make sense to actually add any more methods to
QXmppPresence. As I see it, it would be enough for `QXmppMucRoom::join()`
to probably have an optional parameter of a variant type (as in
boost.variant, too bad we can't use it here) that would define the
discussion history. `QXmppMucRoom::join()` could just append the required
element via `QXmppStanza::setExtensions()`.

**Comment by jlaine** [comment]
I am not convinced a variant type would be the most descriptive. Another option would be an optional QXmppMucHistoryOptions object with some members:

- maxchars
- maxstanzas
- seconds
- since

Can you have a look in Qt to see if you can find a similar API for inspiration?

**Comment by 0xd34df00d** [comment]
Jeremy, I misread the docs as if only one option is allowed at a time.
Variant type is not up to the task then, and I agree with you on your
suggestion.

**Comment by LightZam** [comment]
my idea is like you describe here,
i will do it by implement an object which contains maxchars, maxstanzas, seconds, since data member in QXmppPresence

**Comment by 0xd34df00d** [comment]
I would suggest avoiding storing it inside QXmppPresence.

After all, all those options have nothing to do with presences in general,
they are merely a part of the joining process.

**Comment by jlaine** [comment]
I agree with Georg, let's not touch QXmppPresence's API if it can be helped.

**Comment by LightZam** [comment]
how is it possible no touch QXmppPresence?
Maybe QXmppPresence needs refactor to polymorphism likes QXmppIq does?

**Comment by jlaine** [comment]
No, as Georg mentioned you can use QXmppPresence::setExtensions to add arbitrary XML nodes inside the presence.

**Comment by LightZam** [comment]
okay, i will check how it works.

**Comment by LightZam** [comment]
QXmppPresence::setExtensions is exactly the way to achieve my goal.
i can use it to make any presence,
thank you, Jeremy and Georg, for supporting me
