### ISSUE TITLE
Undefined references on Windows 7(x64) using QXMPP with Speex, Theora and VPX

### ISSUE THREAD

**Issue by IronRider** [qxmpp-project/qxmpp#59]
Hi there.
I try to create qxmpp client with jingle support. I have downloaded and compiled QXMPP using Speex, Theora, VPX using this instruction http://hipersayanx.blogspot.com.ar/2014/07/compile-qxmpp-in-windows-with-full.html
After a compilation I get win32 folder with libqxmpp.a inside. Then I have created a new Qt project and included qxmpp lib in .pro file. When I try to create QxmppLogger object I get theese errors:

undefined reference to `_imp___ZN11QXmppLogger9getLoggerEv'
undefined reference to`_imp___ZN11QXmppLogger14setLoggingTypeENS_11LoggingTypeE'

When I try to create QxmppClient object I get theese errors:

undefined reference to `_imp___ZN11QXmppClientC1EP7QObject'
undefined reference to`_imp___ZN11QXmppClientD1Ev'
undefined reference to `_imp___ZN11QXmppClientD1Ev'

And so on.

Qt uses mingw 4.1, the version of mingw from example above is 3.8. I thougth, this is the problem, so i tried to recompile QXMPP using mingw 4.1 (from qt folder), but it had no affect.
I'am using Windows 7 x64, Qt5, MinGW 4.1.

Thank you in advance.

**Comment by IronRider** [comment]
I tried to recompile OGG, Speex, Theora and VPX one more time. When I try to compile QXMPP with Qt Creator and theese libraries i get an error: "definition of static data member 'QXmppLogger::m_logger' of dllimport'd class"

What am I doing wrong?

**Comment by jlaine** [comment]
Have you tried simply compiling QXmpp and checking whether the tests run?

**Comment by car3tak3r** [comment]
Same issue here in a simple Test-Project based on EchoClient Example on Win10 x64, Qt5.4.2. When Building QXMpp with QtCreator I can select any example from ProjectTree and it runs without Problems. I think this is related to .pro-File Settings and static/shared lib misconfiguration. Will Report back once it's resolved in my poject.

**Comment by lnjX** [comment]
Speex, theora and VPX have been replaced by gstreamer.
