### ISSUE TITLE
SASL 2

### ISSUE THREAD

**Issue by lnjX** [qxmpp-project/qxmpp#606]
XEP: https://xmpp.org/extensions/xep-0388.html

Allows us to implement:
  * Bind 2: https://xmpp.org/extensions/xep-0386.html
  * FAST, token-based authentication: https://xmpp.org/extensions/xep-0484.html
  * SASL Upgrade Tasks: https://xmpp.org/extensions/xep-0480.html

SASL 2 has been implemented in prosody and ejabberd now:
* https://blog.prosody.im/fast-auth/
* https://www.process-one.net/blog/ejabberd-24-02/

Implementation progress:
 * #602
   Restructuring for properly implementing another authentication algorithm without messing up the code all too much.
 * #607

**Funded by [NLnet](https://nlnet.nl/foundation/) via [NGI Zero Entrust](https://nlnet.nl/entrust/).**

**Comment by Neustradamus** [comment]
@lnjX: Good job!

Thanks NLnet to have funded!
