### ISSUE TITLE
Laggy audio in VoIP calls

### ISSUE THREAD

**Issue by IronRider** [qxmpp-project/qxmpp#61]
Hi there. I have compiled QXMPP with SPEEX and VPX libraries. Video went quiet smooth, but audio delay was about one minute.
I have recompiled QXMPP with OPUS and VPX, but nothing has changed. Video still goes smoothly, audio still has delay.
How could I fix this?

**Comment by jlaine** [comment]
As there is no actual audio acquisition / playback done inside QXmpp, could you show us the code you use?

**Comment by jlaine** [comment]
I have been re-reading the code, and I think this might be due to the loop which sends audio RTP packets being clocked by a QTimer, which possibly introduces drift over time.

**Comment by lnjX** [comment]
I don't think this is still a problem as the code has been rewritten / is using gstreamer now.
