### ISSUE TITLE
XEP-0386: Bind 2

### ISSUE THREAD

**Issue by lnjX** [qxmpp-project/qxmpp#614]
https://xmpp.org/extensions/xep-0386.html

- [x] Bind2/Core: Resource binding
  - [x] Implement parsing of Bind 2 elements (without bind2 extensions)
  - [x] OutgoingClient/Sasl2Manager: Use bind2 resource binding
  - [x] Test resource binding with real-world server (ejabberd)
  - [x] Config: Add option for custom resource *tag*
- [x] Bind2/Stream Management: [XEP-0198: Stream Management](https://xmpp.org/extensions/xep-0198.html)
  - [x] parsing of bind2 sm extensions
  - [x] parsing of sasl2 sm extensions
  - [x] enabling of stream management via bind2
  - [x] stream resumption through sasl2
  - [x] real world resumption test (done; found out that old implementation wasn't working, now both work)
- [x] Bind2/Carbons: [XEP-0280: Message Carbons](https://xmpp.org/extensions/xep-0280.html)
  - [x] Enable carbons (interaction with CarbonManagerV2) via bind2
- [x] Bind2/CSI: [XEP-0352: Client State Indication](https://xmpp.org/extensions/xep-0352.html)
  - [x] create internal CsiManager in OutgoingClient
  - [x] Set initial CSI state via bind2

Pull-request:
* #622

**Comment by Neustradamus** [comment]
@lnjX: Good job!
