### ISSUE TITLE
can't build lib for iphoneos-clang

### ISSUE THREAD

**Issue by LightZam** [qxmpp-project/qxmpp#62]
does qxmpp support build ios static lib?

i can build android armv7, macosx_clang

but when i build iphoneos_clang

i got compile error like

    /qxmpp/src/base/QXmppStream.cpp:124: error: member access into incomplete type 'QSslSocket'
    if (!d->socket || d->socket->state() != QAbstractSocket::ConnectedState)
                               ^
    ...

    ../../../../Qt/5.3/ios/include/QtCore/qobject.h:198: candidate function not viable: cannot convert argument of incomplete type 'QSslSocket *' to 'const QObject *'
    static QMetaObject::Connection connect(const QObject *sender, const char *signal,
                                   ^

**Comment by jlaine** [comment]
SSL support is required for QXmpp. However for Qt on iOS, SSL is only enabled by default in Qt 5.5. What version are you using?

**Comment by LightZam** [comment]
i am using Qt 5.3 ... 
if i want to build ios version, it will be necessary to upgrade Qt version.
i will try it later, thank you for your answer.
