### ISSUE TITLE
XEP-0484: Fast Authentication Streamlining Tokens

### ISSUE THREAD

**Issue by lnjX** [qxmpp-project/qxmpp#626]
[XEP-0484: Fast Authentication Streamlining Tokens](https://xmpp.org/extensions/xep-0484.html)

- [x] Parsing of fast xml elements
- [x] Parsing of `HT-<hash>-<cb-type>` SASL mechanism names
- [x] Integrate into SASL 2
- [x] New credentials store
- [x] Implementation of HT- SASL mechanisms

**Comment by Neustradamus** [comment]
To follow :)

**Comment by Neustradamus** [comment]
@lnjX: Good job, thanks!
