### ISSUE TITLE
QXmppClient::connectToServer(const QXmppConfiguration&) is no slot

### ISSUE THREAD

**Issue by Psy-Kai** [qxmpp-project/qxmpp#63]
Hello,

if you use QXmpp in a multithreaded application you have to work arround the problem that there is only one QXmppClient::connectToServer slot. But this resets the QXmppClient::configuation. So please move QXmppClient::connectToServer(const QXmppConfiguration&) from public to public slots.

**Comment by jlaine** [comment]
I agree this should be a slot, I am just not sure whether it would break binary compatibility?
