### ISSUE TITLE
Support Qt4 to improve cross-platform compatibility

### ISSUE THREAD

**Issue by barracuda156** [qxmpp-project/qxmpp#631]
Given the statement in the README:

> QXmpp strives to be as easy to use as possible.

Could support for Qt4 be added? There are platforms where Qt5 is broken completely, and many more where the bleeding-edge 5.15 does not build.

**Comment by barracuda156** [comment]
> For little gain, it would make it impossible to use newer APIs and block the general modernization and keeping up with modern Qt.

I did not mean, of course, that it should be done at expense of newer systems. There are multiple projects which maintain compatibility with Qt4 and Qt5 both, and some also with Qt6. Functionally which cannot be supported in older Qt, can be excluded from respective code-paths.

For the record, the last version here with Qt4 support, 0.9.3, builds fine against the latest versions of all dependencies.

**Comment by barracuda156** [comment]
> Qt4 does not support the connect syntax used everywhere in this project by now.

Well, this is not something I can evaluate. If it gonna require a non-trivial effort, it is arguably not worth.

> I still want to stress that Qt 4 should not be used any more anyway (I am aware you probably have technical reasons why you still use it), and should not be a concern for QXmpp.

This is up to upstream, of course. I would say it is better to rephrase cross-platform part in a case older Qt are not supported though.

P. S. The reason to use Qt4 is simple: Qt5 does not build for my platform, and it is broken on a number of platforms, since, well, its upstream never bothered to write a properly cross-platform code from Qt5 onwards.

**Comment by lnjX** [comment]
> P. S. The reason to use Qt4 is simple: Qt5 does not build for my platform, and it is broken on a number of platforms, since, well, its upstream never bothered to write a properly cross-platform code from Qt5 onwards.

What platform is that? And what application would want to use a modern QXmpp version with an unsupported Qt version, probably with security vulnerabilities?

> Given the statement in the README:
> > QXmpp strives to be as easy to use as possible.

Easy-to-use and cross-platform doesn't mean that we support historical dependency versions or support every platform in the world.

Supporting Qt 4 is not realistic. We're using many Qt 5 features, also including crypto stuff like hmac and hashing algorithms like SHA2/SHA3, the used regular expressions are not compatible between Qt 4 and Qt 6, connect syntax and string handling. The question is rather when we can drop Qt 5 support to use stuff like QAnyStringView.

Everything of that could of course be solved in some way, but I doubt anyone would realistically need it. If you want to develop retro software, you can use QXmpp 0.9.3.

**Comment by lnjX** [comment]
:) Yes and my main point is that I don't see a use-case of having a modern QXmpp version with a very outdated Qt version.

**Comment by barracuda156** [comment]
> :) Yes and my main point is that I don't see a use-case of having a modern QXmpp version with a very outdated Qt version.

MacOS 10.6 and earlier have no Qt5 at all at the moment (and yes, they are used and we maintain ports for them in MacPorts), much later ones still do not support modern Qt5, being stuck at an early version.
Some components of Qt5 are generally broken on some archs: for example, neither WebKit nor WebEngine build on the current OpenBSD on powerpc.

So use-cases are there, just for the record. Though not everything will work out-of-the-box, at least web-related stuff.
