### ISSUE TITLE
Read more from socket than the socks 5 negotation stream

### ISSUE THREAD

**Issue by asergiu** [qxmpp-project/qxmpp#64]
The socks5 negotiation protocol is a standard and it is well known how many bytes are send and how many received from server during handshake. The problem I found is with readAll() method from line 171 which reads all available data from the socket. At this moment the server could have started the file transfer and the socket may contain some file content. This generated file corrupted error on the client side because the beginning of the file is consumed before (in the handshake part, line 171). I resolved the problem as shown below. The standard size of the 2nd response of the server is 47 bytes, so I read from socket only that amount of data(only the response)

diff --git a/Client-QXmpp/src/base/QXmppSocks.cpp b/Client-QXmpp/src/base/QXmppSocks.cpp
index 82ccd09..7b8ede6 100644
--- a/Client-QXmpp/src/base/QXmppSocks.cpp
+++ b/Client-QXmpp/src/base/QXmppSocks.cpp
@@ -168,7 +168,8 @@ void QXmppSocksClient::slotReadyRead()
         disconnect(this, SIGNAL(readyRead()), this, SLOT(slotReadyRead()));

         // receive CONNECT response
-        QByteArray buffer = readAll();
+        QByteArray buffer = read(47);
         if (buffer.size() < 6 ||
             buffer.at(0) != SocksVersion ||
             buffer.at(1) != Succeeded ||

**Comment by jlaine** [comment]
Interesting catch!

Two things worry me:

- if you are already receiving file data, we might have actually received *all* the file data. In this case, readyRead() will never be emitted again, and we will not process the file data.

One way of fixing this : if we have additional buffered data, emit readyRead() after we emit ready().

- there are several other places where we call readAll()

**Comment by jlaine** [comment]
After re-reading the RFC, I don't understand how you came to the conclusion that the replies have a fixed size : this is not the case. What we could do is to make all our parsing use a QDataStream that operates directly on the socket, so we read the right amount of data, but this is a bigger change..

**Comment by asergiu** [comment]
We will have a deeper look at this and try to come up with a solution. We are a very small IT company and in the free time we like to contribute on opensource projects. We found this bug the hard way when testing qxmpp for some messaging. The message comes actually from one of my developpers tha wrote from my account - but we are only a handflul all in the company.We are going to look deeper into it and come back.
Adrian
