### ISSUE TITLE
failed to build 1.8.0 release

### ISSUE THREAD

**Issue by chenrui333** [qxmpp-project/qxmpp#648]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  In file included from /tmp/qxmpp-20240730-17926-6056eu/qxmpp-1.8.0/build/src/QXmppQt6_autogen/7EM65HM6UG/moc_QXmppAccountMigrationManager.cpp:9:
  /tmp/qxmpp-20240730-17926-6056eu/qxmpp-1.8.0/build/src/QXmppQt6_autogen/7EM65HM6UG/../../../../src/client/QXmppAccountMigrationManager.h:64:16: error: no template named 'unordered_map' in namespace 'std'
      const std::unordered_map<std::type_index, std::any> &extensions() const;
            ~~~~~^
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/10170237038/job/28129000987
relates to Homebrew/homebrew-core#179024

**Comment by lnjX** [comment]
Thanks for reporting. I didn't have the error with the missing unordered_map include locally (also not with clang), I still added it. I could fix some other build errors, though. I hope it works now.
