### ISSUE TITLE
Implement XEP-0198: Stream Management

### ISSUE THREAD

**Issue by dryo** [qxmpp-project/qxmpp#66]
For mobile use stream management can help e.g. in reducing lost messages. See here:

http://op-co.de/blog/posts/mobile_xmpp_in_2014/

I'd love to see it implemented.

**Comment by mostafa88** [comment]
I make 2 scenarios to test stream feature. case#1: unplug the network cable and case#2: disable network adapter in Windows. In both cases after reconnecting to the network, I expect to receive messages that sent when I was offline. Everything is OK in case#1, but in case#2, after re-enable the network adapter I receive the following stream error.
`"<stream:error xmlns:stream=\"http://etherx.jabber.org/streams\"><conflict xmlns=\"urn:ietf:params:xml:ns:xmpp-streams\"/></stream:error>" `
 I think that both cases should handled in a same way, but it seems that there is a little different.

**Comment by olesalscheider** [comment]
@mostafa88 Is the stream resumed in both cases? This error tries to tell you that there is still an active, conflicting connection with the same resource.

**Comment by mostafa88** [comment]
@olesalscheider : In case#1 it resumed and I receive offline messages. but in case#2, it not resumed and I lost the offline messages.

**Comment by olesalscheider** [comment]
Ok, but does qxmpp try to resume the stream and this fails or doesn't it even try?

**Comment by mostafa88** [comment]
I'm not sure it try or not, To describe problem better, I write the flow of QXMPP message after reconnect. 

**QXMPP** bind resource `<iq id=\"qxmpp55\" type=\"set\"><bind xmlns=\"urn:ietf:params:xml:ns:xmpp-bind\"><resource>QXmpp</resource></bind></iq>"`
**Server** confirm the resource: <`iq type=\"result\" id=\"qxmpp55\" to=\"ariogames.ir/cyzmhb9ia\"><bind xmlns=\"urn:ietf:params:xml:ns:xmpp-bind\"><jid>20@ariogames.ir/QXmpp</jid></bind></iq>"`

**QXMPP** set session: "`<iq id=\"qxmpp57\" to=\"ariogames.ir\" type=\"set\"><session xmlns=\"urn:ietf:params:xml:ns:xmpp-session\"/></iq>" "<r xmlns=\"urn:xmpp:sm:3\"/>" ` 
**Server** confirm session: `<iq type=\"result\" id=\"qxmpp57\" from=\"ariogames.ir\" to=\"20@ariogames.ir/QXmpp\"/>"`

**QXMPP** enable Stream :` "<enable xmlns=\"urn:xmpp:sm:3\" resume=\"true\"/>"`
**Server** confirm enabling Stream: `"<enabled xmlns='urn:xmpp:sm:3'/>"`

**QXMPP** bind resource and set session again: ```
"<iq id=\"qxmpp55\" type=\"set\"><bind xmlns=\"urn:ietf:params:xml:ns:xmpp-bind\"><resource>QXmpp</resource></bind></iq>"
base\QXmppStream.cpp QXmppStream::sendData 135 "<iq id=\"qxmpp57\" to=\"ariogames.ir\" type=\"set\"><session xmlns=\"urn:ietf:params:xml:ns:xmpp-session\"/></iq>"
base\QXmppStream.cpp QXmppStream::sendData 135 "<r xmlns=\"urn:xmpp:sm:3\"/>"

and after that, QXMPP receive the conflict error:` "<stream:error xmlns:stream=\"http://etherx.jabber.org/streams\"><conflict xmlns=\"urn:ietf:params:xml:ns:xmpp-streams\"/></stream:error>"`
```
I also attached complete output log.
[output.txt](https://github.com/qxmpp-project/qxmpp/files/957855/output.txt)

**Comment by olesalscheider** [comment]
Did you call "QXmppStream::disconnectFromHost()" before reconnecting? If not, can you try it?

The problem seems to be that qxmpp thinks that stream management is active when it sends the first bind and then resends it later when it actually is enabled.

**Comment by mostafa88** [comment]
I Don't call "QXmppStream::disconnectFromHost()" because I don't access to QXmppStream object, I just access to QXmppClient. I think it should be called inside of QXmpp library itself.

**Comment by olesalscheider** [comment]
Can you try this patch please?

https://gist.githubusercontent.com/olesalscheider/6d02e8544fa194113ab0b67c8797faef/raw/8624972acea70dc055d185809e9819a4a0fbaad5/0001-Set-Stream-Management-to-disabled-when-the-socket-be.patch

**Comment by mostafa88** [comment]
The above patch **fix** the problem.
Thanks to @olesalscheider.

**Comment by lnjX** [comment]
This issue should probably be closed.

**Comment by lnjX** [comment]
Stream management has been implemented and the discussed patch has been applied (https://github.com/qxmpp-project/qxmpp/commit/5804795a35d27f8d10301d5f40567a34efca2643).
