### ISSUE TITLE
Different domain name and server

### ISSUE THREAD

**Issue by Thomas-Lerman** [qxmpp-project/qxmpp#67]
I use ejabberd as my XMPP server and have it set up to use blah.something.com for my connect server (advanced settings within the Pidgin client) and something.com as the domain. Not having a current way to do this, I ended up making some changes to be able to specify the connect server then it uses that for the connection if specified otherwise it uses the domain. Did I miss something looking through the code or are you interested me pushing (if that is allowed)?

**Comment by jlaine** [comment]
Hi Thomas,

This is already supported:

```
QXmppConfiguration config;
config.setJid("foo@something.com");
config.setPassword("super_secret");
config.setHost("blah.something.com");

client.connectToServer(config);
```

However if the domain is under your control I would instead *strongly* advise you to learn how to set up the correct DNS SRV records to say that "blah.something.com" serves the XMPP clients for the "something.com" domain:

http://wiki.xmpp.org/web/SRV_Records

That way your users can just connect using JID + password, their client will automatically determine the server to use.

**Comment by Thomas-Lerman** [comment]
Ah, you are correct . . . thank you very much. I am not sure how I missed setHost() . . . I must have been thinking it was something else (not sure what exactly).
