### ISSUE TITLE
GuiClient: Status is not always correct

### ISSUE THREAD

**Issue by Thomas-Lerman** [qxmpp-project/qxmpp#68]
I use ejabberd as my XMPP server. When I used the GuiClient, most of the statuses are incorrect (offline when most are online). I ended up commenting out the lines you see below and then they are correct. I just thought I would pass this along in case others run into this. I am not positive if this is the best fix or not, but it allows the updatePresence() to create the therefore set the presence (otherwise, it gets created later without the presence).

void mainDialog::presenceChanged(const QString& bareJid, const QString& resource)
{
    if(bareJid == m_xmppClient.configuration().jidBare())
        return;

```
//if(!m_rosterItemModel.getRosterItemFromBareJid(bareJid))
//    return;

QString jid = bareJid + "/" + resource;
QMap<QString, QXmppPresence> presences = m_xmppClient.rosterManager().
                                         getAllPresencesForBareJid(bareJid);
m_rosterItemModel.updatePresence(bareJid, presences);
/* . . . */
```

}

**Comment by jlaine** [comment]
Could you provide a dump of the XML stanzas exchanged with the server?

**Comment by Thomas-Lerman** [comment]
I will see what I can do. The difficulty is that it is quite a large set of messages with all of our users. They show up whether they are logged on or not. Sanitizing might not be fun.

**Comment by jlaine** [comment]
I do not understand your reply: I do not want the server side dump, just a client side dump for a single connection. Since it is your server you can create some disposable accounts

**Comment by Thomas-Lerman** [comment]
When I log in, the client side dump is quite long (as in 556 lines long). It is true that it is our server, I do not have permissions to do much. I was able to get our IT guy to create a test account for me.

In any case, I believe the following might be useful . . . if it is not, I will have to try something else. After logging on, I "Show XML Console..." and the following are the only XML stanzas that have my test user in them. With the code commented out as mentioned in my original post, that user is correctly shown as "Available". With that code uncommented, that user is incorrectly shown as "Offline".

```
<presence from="thomas1@something.com/1845040751440817951313250" to="thomas2@something.com/QXmpp">
  <priority>1</priority>
  <c node="http://pidgin.im/" xmlns="http://jabber.org/protocol/caps" ver="I22W7CegORwdbnu0ZiQwGpxr0Go=" hash="sha-1"/>
  <x xmlns="vcard-temp:x:update">
    <photo/>
  </x>
  <delay xmlns="urn:xmpp:delay" from="thomas1@something.com/1845040751440817951313250" stamp="2015-08-29T07:19:33Z"/>
  <x xmlns="jabber:x:delay" stamp="20150829T07:19:33"/>
</presence>

<iq from="thomas2@something.com" type="result" to="thomas2@something.com/QXmpp" id="qxmpp111">
  <query xmlns="jabber:iq:roster">
    <item subscription="both" name="Thomas" jid="thomas1@something.com">
      <group>something</group>
    </item>
  </query>
</iq>
```
Does that help you?

**Comment by Thomas-Lerman** [comment]
I again apologize for editing the previous message so much. I have an update. I would guess this server just does things in a different order. It does the presence before the roster as mentioned above. Without the code in the original post, rosterItemModel::updateRosterEntry() is the one that does the getOrCreateItem() after the presence has been effectively skipped. With my suggestion, but knowing that might not be the best solution, mainDialog::presenceChanged() ends up doing the getOrCreateItem().

**Comment by lnjX** [comment]
The gui client example has been removed.
