### ISSUE TITLE
Example3: unable to transfer file

### ISSUE THREAD

**Issue by Thomas-Lerman** [qxmpp-project/qxmpp#69]
I am trying the third example and am wondering if I am missing something just as silly as I did in #67. I have set up the configuration correctly. I have set it up like:

QXmppConfiguration config;
config.setJid("foo@something.com");
config.setPassword("super_secret");
config.setHost("blah.something.com");

client.connectToServer(config);

and then in the constructor of the xmppClient, I am using the following to set up the "File Transfer Proxies" (as Pidgin calls it within the advanced settings):

    // add transfer manager
    transferManager = new QXmppTransferManager;
    //transferManager->setProxy("proxy.qxmpp.org");
    transferManager->setProxy("blah.something.com");
    addExtension(transferManager);

I then end up with the following in the console (after I accept the send to a user on Pidgin):

Sat 15. Aug 00:08:18 2015 RECEIVED <iq from='blah.something.com' to='foo@something.com
/QXmpp' type='error' id='qxmpp11'><query xmlns='http://jabber.org/protocol/bytes
treams' sid='<sid is in here>'/><error code='501' type='cancel'>
<feature-not-implemented xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>

I can do the file transfers from Pidgin, so would guess I have made a silly error.

------------
I also took a look at receiving a file. It appeared like it was receiving, but I could not find the file. I looked through some code and believe I see why. It is never saving the file name. Within slotFileReceived(), I used the other accept() method and it saved the file. Do I have something else set up incorrectly?

    // allocate a buffer to receive the file
    //QBuffer *buffer = new QBuffer(this);
    //buffer->open(QIODevice::WriteOnly);
    //job->accept(buffer);
    job->accept(job->fileName());

**Comment by jlaine** [comment]
I did not understand what was working, and what was not, could you clarify please?

**Comment by Thomas-Lerman** [comment]
Sorry, I just realized the XML I sent above got lost. Using the file transfer proxy as described above in example_3_transferHandling, I am able to receive a file, but I cannot send a file.

The following shows the last few displayed messages in my console with the last one indicating the error. Does this make better sense?

```
Thu 27. Aug 17:57:10 2015 SENT <iq id="qxmpp13" to="thomas1@something.com/35301128511440719876731246" type="set"><si xmlns="http://jabber.org/protocol/si" id="ivHzist3FOVwqzfxrKerFwHs7zTqQdIq" profile="http://jabber.org/protocol/si/profile/file-transfer"><file xmlns="http://jabber.org/protocol/si/profile/file-transfer" date="2015-08-12T20:09:34.491Z" hash="8c9ab40c7ff7ac03e52161d5f387b13a" name="README" size="297"><desc>example source code</desc></file><feature xmlns="http://jabber.org/protocol/feature-neg"><x xmlns="jabber:x:data" type="form"><field type="list-single" var="stream-method"><option><value>http://jabber.org/protocol/ibb</value></option><option><value>http://jabber.org/protocol/bytestreams</value></option></field></x></feature></si></iq>
Thu 27. Aug 17:57:17 2015 RECEIVED <iq from='thomas1@something.com/35301128511440719876731246' to='thomas2@something.com/QXmpp' type='result' id='qxmpp13'><si xmlns='http://jabber.org/protocol/si'><feature xmlns='http://jabber.org/protocol/feature-neg'><x xmlns='jabber:x:data' type='submit'><field var='stream-method'><value>http://jabber.org/protocol/bytestreams</value></field></x></feature></si></iq>
Thu 27. Aug 17:57:17 2015 SENT <iq id="qxmpp15" to="blah.something.com" type="get"><query xmlns="http://jabber.org/protocol/bytestreams" sid="ivHzist3FOVwqzfxrKerFwHs7zTqQdIq"/></iq>
Thu 27. Aug 17:57:17 2015 RECEIVED <iq from='blah.something.com' to='thomas2@something.com/QXmpp' type='error' id='qxmpp15'><query xmlns='http://jabber.org/protocol/bytestreams' sid='ivHzist3FOVwqzfxrKerFwHs7zTqQdIq'/><error code='503' type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
```

**Comment by jlaine** [comment]
Are you sure about your proxy setup? blah.something.com is responding with an error. Have you tried without the proxy?

**Comment by Thomas-Lerman** [comment]
Thank you! I just tried without the proxy and it works. That does confuse me just a bit as within Pidgin, under "Advanced", "File transfer proxies", I am required to put "blah.something.com". Although they sound like the same thing, maybe they have different meanings???

**Comment by jlaine** [comment]
No idea, I'll let you investigate. Also, instead of hardcoding a proxy you might consider using XMPP Service Discovery to automatically discover the proxy (if any) on your server.
