### ISSUE TITLE
0.9.0+: error: invalid use of member function (did you forget the '()' ?) 

### ISSUE THREAD

**Issue by DAP-DarkneSS** [qxmpp-project/qxmpp#71]
The latest git snapshot, openSUSE with gcc 4.8 or 5.1 both provide the same build time issue:

[   99s] + qmake PREFIX=/usr LIBDIR=lib64 QMAKE_STRIP= 'QMAKE_CXXFLAGS+=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g' QXMPP_USE_VPX=1 QXMPP_USE_SPEEX=1 QXMPP_USE_THEORA=1
…
[  102s] g++ -c -pipe -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -O2 -Wall -W -D_REENTRANT -fPIC -DQXMPP_USE_SPEEX -DQXMPP_USE_THEORA -DQXMPP_USE_VPX -DQXMPP_SHARED -DQXMPP_BUILD -DQT_NO_DEBUG -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtXml -I/usr/include -Ibase -Iclient -Iserver -I. -o QXmppDiscoveryIq.o base/QXmppDiscoveryIq.cpp
[  103s] base/QXmppCodec.cpp: In member function 'virtual QList<QXmppVideoFrame> QXmppVpxDecoder::handlePacket(const QXmppRtpPacket&)':
[  103s] base/QXmppCodec.cpp:1221:35: error: invalid use of member function (did you forget the '()' ?)
[  103s]              || packet.sequence == sequence) {
[  103s]                                    ^
[  103s] base/QXmppCodec.cpp:1225:42: error: invalid use of member function (did you forget the '()' ?)
[  103s]              sequence = packet.sequence + 1;
[  103s]                                           ^
[  103s] base/QXmppCodec.cpp:1234:39: error: invalid use of member function (did you forget the '()' ?)
[  103s]                  || packet.sequence == sequence) {
[  103s]                                        ^
[  103s] base/QXmppCodec.cpp:1236:46: error: invalid use of member function (did you forget the '()' ?)
[  103s]                  sequence = packet.sequence + 1;
[  103s]                                               ^
[  103s] base/QXmppCodec.cpp:1240:36: error: invalid use of member function (did you forget the '()' ?)
[  103s]              if (packet.sequence == sequence) {
[  103s]                                     ^
[  103s] base/QXmppCodec.cpp: At global scope:
[  103s] base/QXmppCodec.cpp:1261:67: warning: unused parameter 'parameters' [-Wunused-parameter]
[  103s]  bool QXmppVpxDecoder::setParameters(const QMap<QString, QString> &parameters)
[  103s]                                                                    ^
[  103s] Makefile:631: recipe for target 'QXmppCodec.o' failed
[  103s] make[1]: *** [QXmppCodec.o] Error 1

**Comment by jlaine** [comment]
Ouch, CI should have caught that. Looks as though pour CI setup is not building all codecs.
