### ISSUE TITLE
Dnslookup issue on linux g++ 64 bit

### ISSUE THREAD

**Issue by gakwaya** [qxmpp-project/qxmpp#72]
Hello ,
I am trying to build a project on linux 64 bit system(ubuntu) using qxmpp,I am getting a crash when the client connects to the server and my debugging has pointed to problems in dns lookup.I have included the files from /src/base and  /src/client in my project as .The dns part simply mimics your base.pri  section like this ;

qt_version = $$QT_MAJOR_VERSION
contains(qt_version, 4) {
    INSTALL_HEADERS += ../../QXmpp/qxmpp-master/src/base/qdnslookup.h
    INSTALL_HEADERS += ../../QXmpp/qxmpp-master/src/base/qdnslookup_p.h
    SOURCES += ../../QXmpp/qxmpp-master/src/base/qdnslookup.cpp
    android:SOURCES += ../../QXmpp/qxmpp-master/src/base/qdnslookup_stub.cpp
    else:symbian:SOURCES += ../../QXmpp/qxmpp-master/src/base/qdnslookup_symbian.cpp
    else:unix:SOURCES += ../../QXmpp/qxmpp-master/src/base/qdnslookup_unix.cpp
    else:win32:SOURCES += ../../QXmpp/qxmpp-master/src/base/qdnslookup_win.cpp
    else:SOURCES += ../../QXmpp/qxmpp-master/src/base/qdnslookup_stub.cpp
}

I have seen that you have succesfully tested on linux g++ 64 bit ,so it must be me messing up somewhere and I would appreciate any hint.Here is my debug window.I have to mention that it is working ok when I build on my windows 7 64 bit environment.

![screenshot from 2015-08-31 14 02 28](https://cloud.githubusercontent.com/assets/3991041/9573000/35a7b3ae-4fe9-11e5-886a-aa86890246f7.png)

Thank you for your time.

**Comment by jlaine** [comment]
What version of Qt are you using? Qt4 or Qt5?

**Comment by gakwaya** [comment]
Thanks for the quick reply ,
I am using Qt 5.5 0.

**Comment by jlaine** [comment]
In that case you should definitely not be compiling / including / using the qdnslookup* files provided with QXmpp, you can rip them out of your project. The QDnsLookup class has been integrated into Qt5.

**Comment by gakwaya** [comment]
Thanks a bunch :-) ,it is building now .By the way ,I also want to provide an option to build the project linking to already built binaries ,but I could not figure out how to link.On windows with mingw when you build the qxmpp as a library , qxmpplib.a and qxmpp.dll are generated and I link against them with simple LIBS directives in the .pro file.When I built them on linux I got these binaries :libqxmpp_d.so   ,libqxmpp_d.so.0 , libqxmpp_d.so.0.8  and libqxmpp_d.so.0.8.3 .Which one do I link against and how do I do it.I realize this is basic but a quick tip always saves time :-).
Thanks again.
