### ISSUE TITLE
[Question] get roster when connected 

### ISSUE THREAD

**Issue by LightZam** [qxmpp-project/qxmpp#74]
i think developer should has the chance to disable automatic get roster when connected, sometimes it will reconnect by network problem, but developer do not want get roster again

QXmppRosterManger.cpp

```
check = connect(client, SIGNAL(connected()),
                this, SLOT(_q_connected()));

void QXmppRosterManager::_q_connected()
{
    QXmppRosterIq roster;
    roster.setType(QXmppIq::Get);
    roster.setFrom(client()->configuration().jid());
    d->rosterReqId = roster.id();
    if (client()->isAuthenticated())
        client()->sendPacket(roster);
}
```

if you agree this opinion, i will pull request

**Comment by 0xd34df00d** [comment]
IMO it is good to always get a full version of the roster on connect just
in case it was modified during that short disconnect period.

A better solution for conserving bandwidth is to implement
http://xmpp.org/extensions/xep-0237.html and use servers supporting this
XEP.

**Comment by LightZam** [comment]
okay, it looks like this effort belong to server side...

**Comment by lnjX** [comment]
Another solution is, if you don't want to use the roster at all (for example as a bot only sending messages), you can also disable the roster manager completely by removing the extension.

The proper issue for roster versioning can be found here #164, so I'm closing this.
