### ISSUE TITLE
QXmppClient::sentPacket won't work with threads

### ISSUE THREAD

**Issue by Psy-Kai** [qxmpp-project/qxmpp#75]
Hello,

if you use `QXmppClient` in another thread the slot `QXmppClient::sentPacket(const QXmppStanza&)` wont work. You can not use `qRegisterMetaType<T>(const char*)` with abstract types and `QXmppStanza` ist abstract. ~~Is it possible to implement `QXmppStanza::toXml(QXmlStreamWrite *)` with:~~

>    virtual QXmppStanza::toXml(QXmlStreamWriter *writer) const
>    {
>        Q_UNUSED(writer);
>    }

~~Or is it important to have `toXml` pure virtual?~~

**Comment by jlaine** [comment]
What do you mean "won't work with threads"? Why would you call this from a thread other than the one the QXmppClient lives in?

**Comment by Psy-Kai** [comment]
Let me show you an example:
    class MyXmppConnection
    {
    public:
        MyXmppConnection()
        {
            QThread *t(new QThread());
            this->moveToThread(t);
            client_.moveToThread(t);
            QObject::connect(this, &MyXmppConnection::sendPacket_sig, &client_, &QXmppClient::sendPacket);
            t->start();
        }
        void sendMessage(const QString &msg)
        { emit sendPacket_sig(QXmppMessage(QString("from value"), QString("to value"), QString("data to send")))); }
    signals:
        void sendPacket_sig(const QXmppStanza &stanza);
    private
        QXmppClient client_;
    }

So when some functions is calling `MyXmppConnection::sendMessage`, it is defenetly from another thread. To prevent errors I need to emit `MyXmppConnection::sendPacket_sig`. Then `QXmppClient::sendPacket` is called in the thread were QXmppClient lives in.

And yes, I need to use `QXmppClient::sendPacket` because I want to send a Message to a specific client, not to all with that bare jid.

PS: In my application this sendMessage function is also a slot. But to prevent wrong usage I emit a signal.

**Comment by Psy-Kai** [comment]
Ok making `QXmppStanza` not abstract wont solve the problem, sorry my fault. Qt can not queue base classes :( 

`QSharedPointer<SomeBaseClass>` can be queue. But I think nobody would get happy with this solution.

**Comment by jlaine** [comment]
I still don't understand the usecase : why do you need to move the QXmppClient off the main thread? If for some odd reason you absolutely must move QXmppClient to a thread, just make sure you do your packet sending on that thread too.

**Comment by lnjX** [comment]
QXmppClient is not supposed to work across different threads.
