### ISSUE TITLE
QXMPP extensions not calling

### ISSUE THREAD

**Issue by balancin** [qxmpp-project/qxmpp#77]
I'm making one xmpp client and I have a lot doubts in extensions .. 

I did need get a list of old messages with one user, so .. I'm using the QXmppArchiveManager class for that. So I make one class like that:

    ...
    
    class QXmppArchiveManager;
    class MessageController : public QXmppClient
    {
    ...

    private:
        QNetworkAccessManager *nam_;
        QXmppClient *xmppClient_;
        QXmppArchiveManager *archiveMng_;
        QDateTime m_startDate;
        QDateTime m_endDate;

    protected slots:
        virtual void onConnected();
        virtual void onMessageReceived(const QXmppMessage &);
        virtual void archiveListReceived(const QList<QXmppArchiveChat> &chats, const QXmppResultSetReply &rsmReply);
    }

And implements

    ...
    void MessageController::onConnected() //before client connects listener...
    {
    
        QXmppResultSetQuery rsmQuery;
        rsmQuery.setMax(0);
        m_startDate = QDateTime::currentDateTime().addDays(-201);
        m_endDate = QDateTime::currentDateTime();
    
        archiveMng_->listCollections("", m_startDate, m_endDate, rsmQuery);
    
    }

    void MessageController::connect()
    {
    
        xmppClient_ = new QXmppClient();
        QObject::connect( xmppClient_, SIGNAL( connected() ), this, SLOT( onConnected() ) );
        QObject::connect( xmppClient_, SIGNAL( messageReceived( QXmppMessage ) ), this, SLOT( onMessageReceived( QXmppMessage ) ) );

        archiveMng_ = new QXmppArchiveManager;
        xmppClient_->addExtension(archiveMng_); 

        QObject::connect(archiveMng_, SIGNAL(archiveChatReceived(QXmppArchiveChat, QXmppResultSetReply)),
                        SLOT(archiveChatReceived(QXmppArchiveChat, QXmppResultSetReply))); 

        QObject::connect(archiveMng_, SIGNAL(archiveListReceived(QList<QXmppArchiveChat>, QXmppResultSetReply)),
                    SLOT(archiveListReceived(QList<QXmppArchiveChat>, QXmppResultSetReply))); 

        xmppClient_->logger()->setLoggingType( QXmppLogger::StdoutLogging );  
    
        QXmppConfiguration config;
    
        config.setDomain("(censored)");
        config.setHost("(censored)");
        config.setPort(5222);
        config.setUser((censored));
        config.setPassword((censored));
        config.setResource("Android-Client");
    
        xmppClient_->connectToServer( config );
    
    }

    void MessageController::archiveChatReceived(const QXmppArchiveChat &chat, const QXmppResultSetReply &rsmReply)
    {
        qDebug() << "archiveChatReceived";
    }
    
    void MessageController::archiveListReceived(const QList<QXmppArchiveChat> &chats, const QXmppResultSetReply &rsmReply)
    {
        qDebug() << "archiveListReceived";
    }

The problem is ... this code not called this listeners, in this case not call "archiveListReceived".

How I can fix that ?

Thanks

**Comment by jlaine** [comment]
Please provide a dump of the XML exchanged between client and server. Most likely your server does not support message archiving.

**Comment by balancin** [comment]
I found it, in this case my openfire xmpp server not working for archive, so ... I'm install the open archive plugin for it, but ... not working correctly yet, it responses but with no results:

SENT <iq id="qxmpp11" type="get"><list xmlns="urn:xmpp:archive" start="2015-03-06T13:10:55.728Z" end="2015-09-23T13:10:55.728Z"><set xmlns="http://jabber.org/protocol/rsm"><max>30</max></set></list></iq>

RECEIVED <iq type="result" id="qxmpp11" to="55b5cdcf0364d17169728758@blimps1/Android-Client"><list xmlns="urn:xmpp:archive"><chat with="55a288f4a0eed1c94d4842f6@blimps1" start="2015-09-23T08:47:06.478Z"/><set xmlns="http://jabber.org/protocol/rsm"><first index="0">1</first><last>1</last><count>1</count></set></list></iq>

**Comment by jlaine** [comment]
This was a server configuration issue
