### ISSUE TITLE
MUC signals

### ISSUE THREAD

**Issue by Thomas-Lerman** [qxmpp-project/qxmpp#80]
Been playing with MUC. I noticed the following issues / suggestions:
1. invitationReceived(): do not seem to get triggered, seem to have similar problems with kick() and ban().
2. subjectChanged(): has new subject, would be nice if also passed the nickname of who changed it and what the old subject was.
3. I have not found the ability to delete a subject (topic).
4. nameChanged(): has new name, would be nice if also passed the nickname of who changed it and what the old name was.
5. nickNameChanged(): has new nickname, would be nice if also passed the old nickname.
6. Maybe ability exists, but I have not found how to send a private message through a MUC (Pidgin uses /msg).
7. participantChanged(): never seems to be triggered. Is this for when a participant changes nicknames? Changing nicknames seems to generate a leaving of the MUC and rejoin.
8. Similar to Pidgin . . . Do we have the ability to set, change, or delete my "mood"? How about handling a "me"?

**Comment by jlaine** [comment]
An issue containing 8 separate issues is not great, if you want to start a discussion there is a mailing list.

1, 7 : For the signals you claim are not triggered, please provide a dump of the XML stanzas exchanged with the server and open a new issue.

2, 4, 5 : For the XxxChanged signals: these signals are there to provide a simple and familiar Q_PROPERTY based interface. I do not plan to change the signature of these signals as it would break backwards compatibility. You could argue for any number of new arguments to be added, but in the end if you want to capture *all* the information, you will most likely want to handle the incoming message/presence/iq yourself.

3 : If by "delete a subject" you mean "set an empty subject", it's just QXmppMucRoom::setSubject with an empty argument.

6 : read XEP-0045, it just a message to room@service/nick

8 : no idea, XEP-0045 has no concept of mood
