### ISSUE TITLE
Request: MUC private message

### ISSUE THREAD

**Issue by Thomas-Lerman** [qxmpp-project/qxmpp#82]
Request for MUC private message support. I have included the XML to illustrate the difference between public (groupchat) and private (chat). The only difference I see it the <message type> and <active>. It seems like this might be able to reuse the sendMessage() method and maybe a new privateMsg parameter that is defaulted to false.

```
<message from="soft@conference.think-thomas/thomasl" type="groupchat" id="purpleebb345b6" to="admin@think-thomas/QXmpp">
  <body>public</body>
</message>
```

```
<message from="soft@conference.think-thomas/thomasl" type="chat" id="purpleebb345b8" to="admin@think-thomas/QXmpp">
  <active xmlns="http://jabber.org/protocol/chatstates"/>
  <body>private</body>
</message>
```

P.S. The other half of this would be indicating a received message was a private message.

**Comment by 0xd34df00d** [comment]
It is already implemented, with one having to construct the QXmppMessage with the proper destination, and that's it.

**Comment by Thomas-Lerman** [comment]
I am currently using the following to send a message through a chat room:
```
	room->sendMessage(msg);
```
and the following for non-chat rooms:
```
	m_xmppClient.sendMessage(nick, msg);
```
So, what I am requesting is a change to these (which I realize might be helper methods) or something similar. Does this still take care of the incoming messages as well? I might be missing something.

**Comment by Thomas-Lerman** [comment]
Okay, I believe I understand what 0xd34df00d was talking about now (sorry about that):

Send Message:
```
	QXmppMessage msg;
	msg.setBody(text);
	msg.setFrom(room->jid() + "/" + room->nickName());
	msg.setTo(room->jid() + "/" + nick);
	msg.setType(QXmppMessage::Chat);
	xmppClient.sendPacket(msg);
```
Then on the receiving end:
```
	msg.type() == QXmppMessage::Chat
```
would tell me the message was a private chat instead of a QXmppMessage::GroupChat.

Again, I suppose this can be closed although I would still suggest it to be maybe slightly easier like specifying it a private message with something like room->sendMessage(msg, nick);

**Comment by lnjX** [comment]
Closing as there's nothing to do here.
About the suggestion: I don't think `room->sendMessage()` in general is such a good idea since you can't send any message extensions. PRs/ideas are welcome.
