### ISSUE TITLE
how to using doxygen? i got error when i try to do that

### ISSUE THREAD

**Issue by LightZam** [qxmpp-project/qxmpp#84]
i am using qt creator with QXMPP_USE_DOXYGEN=1 android ndk = r10e, and build it with qt5.5 android kit, but i get error below? is there something wrong?

	/usr/local/Cellar/android-ndk/r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtbegin_dynamic.o: No such file or directory
	/usr/local/Cellar/android-ndk/r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtend_android.o: No such file or directory
	/usr/local/Cellar/android-ndk/r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc
	/usr/local/Cellar/android-ndk/r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ldl
	../../../../Qt/5.5/android_armv7/include/QtCore/qarraydata.h:53: error: undefined reference to 'qt_assert(char const*, char const*, int)'
	doxyfilter.o(.ARM.extab.text._ZN10QByteArrayD2Ev+0x0): error: undefined reference to '__gxx_personality_v0'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:442: error: undefined reference to 'QString::append(QString const&)'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:508: error: undefined reference to 'QString::toUtf8_helper(QString const&)'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:514: error: undefined reference to 'QString::toLocal8Bit_helper(QChar const*, int)'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:530: error: undefined reference to 'strlen'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:530: error: undefined reference to 'QString::fromUtf8_helper(char const*, int)'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:534: error: undefined reference to 'strlen'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:534: error: undefined reference to 'QString::fromLocal8Bit_helper(char const*, int)'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:650: error: undefined reference to 'strlen'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:650: error: undefined reference to 'QString::fromAscii_helper(char const*, int)'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:878: error: undefined reference to 'qt_assert(char const*, char const*, int)'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:910: error: undefined reference to 'QString::multiArg(int, QString const**) const'
	doxyfilter.o(.ARM.extab.text._ZN7QStringD2Ev+0x0): error: undefined reference to '__gxx_personality_v0'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:1261: error: undefined reference to '__cxa_end_cleanup'
	doxyfilter.o(.ARM.extab.text._ZplRK7QStringS1_+0x0): error: undefined reference to '__gxx_personality_v0'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstring.h:1268: error: undefined reference to '__cxa_end_cleanup'
	doxyfilter.o(.ARM.extab.text._ZplRK7QStringPKc+0x0): error: undefined reference to '__gxx_personality_v0'
	../../../../Qt/5.5/android_armv7/include/QtCore/qlist.h:92: error: undefined reference to 'QListData::dispose(QListData::Data*)'
	../../../../Qt/5.5/android_armv7/include/QtCore/qstringlist.h:192: error: undefined reference to 'QtPrivate::QStringList_join(QStringList const*, QChar const*, int)'
	../../../../Qt/5.5/android_armv7/include/QtCore/qiodevice.h:117: error: undefined reference to 'QIODevice::write(char const*, long long)'
	../../qxmpp/doc/doxyfilter.cpp:39: error: undefined reference to 'QString::arg(QString const&, int, QChar) const'
	../../qxmpp/doc/doxyfilter.cpp:39: error: undefined reference to 'QRegExp::QRegExp(QString const&, Qt::CaseSensitivity, QRegExp::PatternSyntax)'
	../../qxmpp/doc/doxyfilter.cpp:39: error: undefined reference to 'QString::arg(QString const&, int, QChar) const'
	../../qxmpp/doc/doxyfilter.cpp:39: error: undefined reference to 'QString::replace(QRegExp const&, QString const&)'
	../../qxmpp/doc/doxyfilter.cpp:39: error: undefined reference to 'QRegExp::~QRegExp()'
	../../qxmpp/doc/doxyfilter.cpp:39: error: undefined reference to 'QRegExp::~QRegExp()'
	../../qxmpp/doc/doxyfilter.cpp:39: error: undefined reference to '__cxa_end_cleanup'
	../../qxmpp/doc/doxyfilter.cpp:43: error: undefined reference to 'QTextStream::QTextStream(__sFILE*, QFlags<QIODevice::OpenModeFlag>)'
	../../qxmpp/doc/doxyfilter.cpp:44: error: undefined reference to 'QTextStream::operator<<(char const*)'
	../../qxmpp/doc/doxyfilter.cpp:45: error: undefined reference to 'QTextStream::operator<<(char const*)'
	../../qxmpp/doc/doxyfilter.cpp:46: error: undefined reference to 'QTextStream::operator<<(char const*)'
	../../qxmpp/doc/doxyfilter.cpp:47: error: undefined reference to 'QTextStream::operator<<(char const*)'
	../../qxmpp/doc/doxyfilter.cpp:47: error: undefined reference to 'QTextStream::~QTextStream()'
	../../qxmpp/doc/doxyfilter.cpp:47: error: undefined reference to 'QTextStream::~QTextStream()'
	../../qxmpp/doc/doxyfilter.cpp:47: error: undefined reference to '__cxa_end_cleanup'
	../../qxmpp/doc/doxyfilter.cpp:48: error: undefined reference to '__sF'
	../../qxmpp/doc/doxyfilter.cpp:48: error: undefined reference to 'endl(QTextStream&)'
	../../qxmpp/doc/doxyfilter.cpp:52: error: undefined reference to 'QCoreApplication::QCoreApplication(int&, char**, int)'
	../../qxmpp/doc/doxyfilter.cpp:55: error: undefined reference to 'QProcess::execute(QString const&)'
	../../qxmpp/doc/doxyfilter.cpp:61: error: undefined reference to 'strcmp'
	../../qxmpp/doc/doxyfilter.cpp:63: error: undefined reference to 'QProcess::QProcess(QObject*)'
	../../qxmpp/doc/doxyfilter.cpp:64: error: undefined reference to 'QProcess::start(QString const&, QStringList const&, QFlags<QIODevice::OpenModeFlag>)'
	../../qxmpp/doc/doxyfilter.cpp:65: error: undefined reference to 'QProcess::waitForFinished(int)'
	../../qxmpp/doc/doxyfilter.cpp:66: error: undefined reference to 'QMessageLogger::warning(char const*, ...) const'
	../../qxmpp/doc/doxyfilter.cpp:69: error: undefined reference to 'QIODevice::readAll()'
	../../qxmpp/doc/doxyfilter.cpp:74: error: undefined reference to 'QString::operator=(QString const&)'
	../../qxmpp/doc/doxyfilter.cpp:90: error: undefined reference to 'QString::number(int, int)'
	../../qxmpp/doc/doxyfilter.cpp:90: error: undefined reference to 'QString::number(int, int)'
	../../qxmpp/doc/doxyfilter.cpp:90: error: undefined reference to 'QString::number(int, int)'

**Comment by jlaine** [comment]
Cross-compiling won't work, please do a native build for your platform if you *must* generate doxygen documentation yourself. Alternatively use the online documentation:

http://doc.qxmpp.org/
