### ISSUE TITLE
Request: Add the capability to substitute the transport

### ISSUE THREAD

**Issue by zucher** [qxmpp-project/qxmpp#89]
Currently the QSslSocket's are directly created into QXmpp(Incoming|Outgoing)(Client|Server) constructors.

May the QsslSocket's creation be done into an overloadable method called in constructors instead of direct call ?

Thks

**Comment by jlaine** [comment]
What have you got in mind exactly?

FYI, the current architecture is already sufficient to implement QXmppIncomingClient with an HTTP transport:

https://github.com/jlaine/xmpp-share-server/blob/master/src/plugins/QXmppIncomingBosh.h

**Comment by zucher** [comment]
We want to add Xmpp over WebSocket transport support, not forcing socket creation into constructor seems the only possibility.

**Comment by zucher** [comment]
An other point regarding the direction, Xmpp over websocket is as client

**Comment by zucher** [comment]
I take a lot of time to find a solution to generify the transport on QXmmpClient part , without success, I every cases, We must duplicate most of all client folder classes to replace transport, could you confirm @jlaine or do you have some Inputs to give ?
Tks

**Comment by zucher** [comment]
The aim is to support the RFC7395 (see http://docs.ejabberd.im/xmpp/ and https://tools.ietf.org/html/rfc7395 ) as client in order to be more efficient as BOCH comparing to BOCH implementation

**Comment by libergia** [comment]
The support of RFC 7395 would be a great feature. I plan to add this in our application. Can we do something?

**Comment by zucher** [comment]
Unfortunalty, I'm no more working on this implementation, the current stack QXmpp is not enough flexible to allow a transport conversion properly, tcp / ssl is deep hard coded, and object oriented modifications implies a lot of class overiding. A big code refactoring is requiered to propertly achive this RFC implementation.

**Comment by libergia** [comment]
Ok, I see. When will come our needs, maybe we'll look at the details more deeply.
Thanks

**Comment by jlaine** [comment]
Closing as the submitter has lost interest.
