### ISSUE TITLE
Incorrect Invite message format

### ISSUE THREAD

**Issue by mkomadina** [qxmpp-project/qxmpp#93]
I think that format of invite message is incorrect.

Current invite message:
```
<message to=newParticipantBareJid type="normal">
       <x xmlns="jabber:x:conference"  jid=conferenceJid />
</message>
```

How it should be (see http://xmpp.org/extensions/xep-0045.html#registrar-querytypes-invite):
```
<message to=conferenceJid>
  <x xmlns='http://jabber.org/protocol/muc#user'>
    <invite to=newParticipantBareJid/>
  </x>
</message>
```

Problem is in parsing QXmppMessage to xml (QXmppMessage.cpp line 660).

**Comment by jlaine** [comment]
There are two kinds of invites:
- the older mediated invites as defined by XEP-0045 
- the newer direct invites as defined by XEP-0249

QXmpp implements the latter. For the rationale see http://xmpp.org/extensions/xep-0045.html#invite

**Comment by kollix** [comment]
I'm seeing a problem here: http://xmpp.org/extensions/xep-0045.html#invite
describes the mediated invites as: "Mediated invitations were added in Multi-User Chat as a way to handle invitations in the context of members-only rooms"

And exactly when I create a members-only room, using QXmppMucRoom::sendInvitation() does not work (at least with conversations on Android and telepathy on KDE/Linux)

**Comment by jlaine** [comment]
As stated previously, QXmpp does not send XEP-0045 style invitations, it sends direct invites only.

"It does not work" is not a helpful statement, if you expect a useful reply, please give us some usable input.

**Comment by kollix** [comment]
Yes, I know that QXmpp sends direct invites.
My statement was: when having members-only rooms, it should send mediated invitations instead (per XEP-0045).
Or am I wrong ?

The "does not work" statement means: both clients I mentioned did not ask the user to accept the invitation or did something to allow the user to join the room. The result was that the user can simply not use a members-only room.
As I'm not that deep into XMPP as you are, I was hoping that you can tell me if that was a limitation or bug in the clients or that it's a limitation in the fact that QXmpp does only use direct invitations.

**Comment by kollix** [comment]
I have now implemented the sending of a "mediated invitation" directly in my code like this:
`
            QXmppMessage message;
            message.setTo(mucRoom->jid());
            message.setType(QXmppMessage::Normal);

            QXmppElement xElement;
            xElement.setTagName(QLatin1String("x"));
            xElement.setAttribute(QLatin1String("xmlns"), QLatin1String(ns_muc_user));

            QXmppElement invite;
            invite.setTagName(QLatin1String("invite"));
            invite.setAttribute(QLatin1String("to"), qJid);
            xElement.appendChild(invite);

            if ( !qReason.isEmpty() )
            {
              QXmppElement reasonElem;
              reasonElem.setTagName(QLatin1String("reason"));
              reasonElem.setValue(qReason);
              invite.appendChild(reasonElem);
            }

            QXmppElementList extensions;
            extensions << xElement;
            message.setExtensions(extensions);

            ok = client->qxmpp->sendPacket(message);
`

Maybe we should put this as a new method in QXmppMucRoom ?
