### ISSUE TITLE
Some server have difficulty with second <?xml preamble being sent

### ISSUE THREAD

**Issue by vogel** [qxmpp-project/qxmpp#94]
I've encountered one specific XMPP server that does not like second
<?xml preamble in its stream. First one is sent when socket is
unencrypted, then, after encryption is established, second one is sent.

For most servers (including google ones) this is OK, but I have one that
does not like that and closes connection with following error
(truncated):

<xml-not-well-formed /><text>XML or text declaration not at start of
entity</text>

I've made workaround that only sends <?xml version='1.0'?> when connection
is not yet encrypted. What do you think about it?

https://github.com/vogel/qxmpp/commit/71dd9df9d95f6531a925a438fdb89b657471a03e

**Comment by servonic** [comment]
RFC 6120 clearly states in "5.3.2. Restart"
> After TLS negotiation, the parties MUST restart the stream.

Together with "11.5 Inclusion of XML Declaration"
> Before sending a stream header, an implementation SHOULD send an XML
   declaration

I think the behaviour of qxmpp is correct here.
Did you open an issue for that server?

**Comment by vogel** [comment]
Hello.

Thank you for your response. I'm currently trying to get name/version of the server (its identity is hidden behind IT procedures at company of one of users of Kadu) - so it is hard do file issue for it.

Previous versions of Kadu (with libiris) had no problems connecting with that server, as well as some other clients (PSI, Pidgin). It may be that the server is wrong, but I can not fix it...

BTW, this server requires QXmppConfiguration::StreamSecurityMode::LegacySSL. Maybe it has another rules?

**Comment by jlaine** [comment]
I am really not in favour of including hacks in QXmpp which go against the RFCs..

**Comment by vogel** [comment]
I understand. I'll look for another solutions.
