### ISSUE TITLE
using QXmppConstants in windows error

### ISSUE THREAD

**Issue by LightZam** [qxmpp-project/qxmpp#97]
i got "unresolved external symbol 'const char*'" when used ns_muc, etc in QXmppConstants.h in msvc qt

and got compile error when used helperToAddAttribute() in QXmppUntils.h

every platform works fine but windows msvc

is there a solution to workaround?

the Qt version is 5.5.1

**Comment by servonic** [comment]
You can add QXmppConstants.cpp to your own project as this file contains the actual values. 

However keep in mind that this file is licensed under the LGPL (as the whole qxmpp project) and there is (as far as I know) no linking exception for this file. To be safe, I declared constants for the namespaces I needed myself in an own file.

@jlaine is it OK to include QXmppConstants.cpp to an own (non-lgpl) project? If so, could you add a linking exception or other clearification for this file?

**Comment by LightZam** [comment]
@servonic thanks for your reply.
i make constants myself right now to workaround this problem, but i needed to change its name or add namespace to prevent conflict from qxmpp like your advice.

**Comment by jlaine** [comment]
QXmppConstants was never part of the documented API. I have now clarified this with an explicit comment in e489c70d71ced95ba8a3a894125e11ef59554568
